'use strict';
const $=s=>document.querySelector(s), uid=()=>crypto.randomUUID(), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={router:['路由器','ROUTER','<rect x="4" y="10" width="24" height="12" rx="3"/><path d="M9 10V5m14 5V5M9 17h1m4 0h1m4 0h4"/>'],switch:['交换机','SWITCH','<rect x="3" y="9" width="26" height="15" rx="3"/><path d="M7 14h3m3 0h3m3 0h3m3 0h1M7 19h3m3 0h3m3 0h3"/>'],firewall:['防火墙','FIREWALL','<path d="M16 3l11 4v9c0 7-11 13-11 13S5 23 5 16V7zM7 13h18M8 20h16M16 5v8m-5 0v7m10-7v7m-5 0v7"/>'],server:['服务器','SERVER','<rect x="7" y="3" width="18" height="26" rx="3"/><path d="M7 12h18M7 21h18M11 8h1m4 0h5m-10 9h1m4 0h5m-10 9h1"/>'],pc:['电脑','COMPUTER','<rect x="3" y="4" width="26" height="19" rx="2"/><path d="M16 23v5m-7 0h14M3 19h26"/>'],ap:['无线 AP','ACCESS POINT','<circle cx="16" cy="23" r="3"/><path d="M6 14a14 14 0 0120 0M2 9a20 20 0 0128 0M11 19a7 7 0 0110 0"/>'],cloud:['外网 / 云','INTERNET','<path d="M9 24h15a6 6 0 001-12A9 9 0 007 10a7 7 0 002 14z"/>']};
Object.assign(types,{
 region:['区域框','REGION','<rect x="3" y="5" width="26" height="22" rx="3"/><path d="M3 12h26"/>'],
 text:['文本框','TEXT','<path d="M5 6h22M16 6v21M10 27h12M5 6v5m22-5v5"/>'],
 behavior:['上网行为管理','WEB GATEWAY','<rect x="3" y="8" width="26" height="17" rx="3"/><path d="M7 20h18M8 15l4-4 5 6 6-6m-1 0h3v3"/>'],
 ont:['运营商光猫','ONT / MODEM','<rect x="3" y="13" width="26" height="12" rx="3"/><path d="M8 13V5m16 8V5M7 20h1m4 0h1m4 0h1m4 0h3M12 6h8"/>'],
 ac:['无线控制器','WLAN CONTROLLER','<rect x="3" y="16" width="26" height="12" rx="3"/><path d="M7 22h2m3 0h2m6 0h5M9 8a10 10 0 0114 0m-11 4a5 5 0 018 0"/>'],
 loadbalancer:['负载均衡','LOAD BALANCER','<rect x="11" y="3" width="10" height="7" rx="2"/><rect x="2" y="23" width="9" height="6" rx="1"/><rect x="21" y="23" width="9" height="6" rx="1"/><path d="M16 10v7H6v6m10-6h10v6"/>'],
 vpn:['VPN 网关','VPN GATEWAY','<rect x="3" y="15" width="26" height="13" rx="3"/><path d="M11 15V9a5 5 0 0110 0v6M16 20v3M7 22h1m16 0h1"/>'],
 nvr:['监控录像机','NVR / DVR','<rect x="3" y="10" width="26" height="15" rx="3"/><circle cx="9" cy="17" r="2"/><path d="M16 15h9m-9 5h5M7 28h3m12 0h3"/>'],
 camera:['网络摄像机','IP CAMERA','<path d="M4 7h19v12H4zM23 10l6-3v15l-6-4M12 19v7h9m-4 0v-4"/>'],
 nas:['网络存储','NAS / STORAGE','<rect x="5" y="3" width="22" height="26" rx="3"/><path d="M12 7v17m8-17v17M8 25h2m5 0h2m5 0h2"/>'],
 patchpanel:['网络配线架','PATCH PANEL','<rect x="2" y="8" width="28" height="16" rx="2"/><path d="M6 12h4v6H6zm8 0h4v6h-4zm8 0h4v6h-4M6 21h4m4 0h4m4 0h4"/>'],
 converter:['光纤收发器','MEDIA CONVERTER','<rect x="3" y="9" width="26" height="16" rx="3"/><path d="M7 14h7v6H7zm13 1h5m-5 4h5M9 5v4m14-4v4"/>'],
 ups:['不间断电源','UPS','<rect x="7" y="3" width="18" height="26" rx="3"/><path d="M11 7h10v5H11m7 3l-5 7h5l-3 5"/>'],
 printer:['网络打印机','NETWORK PRINTER','<path d="M8 11V3h16v8M8 24H3V11h26v13h-5M8 20h16v9H8zM23 15h2"/>'],
 generic:['通用设备','CUSTOM DEVICE','<rect x="4" y="4" width="24" height="24" rx="5"/><path d="M10 11h12m-12 5h12m-12 5h6"/>']
});
const categories=[['标注',['text','region']],['网络与接入',['router','switch','ont','ap','ac','cloud']],['安全与应用交付',['firewall','behavior','vpn','loadbalancer']],['计算、存储与监控',['server','nas','nvr','camera','pc','printer']],['机房基础设施',['patchpanel','converter','ups','generic']]];
const defaults=[{id:'cat6',name:'六类网线',color:'#5683e8'},{id:'cat6a',name:'超六类网线',color:'#16a88d'},{id:'sm',name:'单模光纤',color:'#e8a33d'},{id:'mm',name:'多模光纤',color:'#a775d9'},{id:'dac',name:'DAC',color:'#6c7b91'}];
const icon=t=>`<svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${types[t][2]}</svg>`;
const blank=()=>({version:1,name:'未命名拓扑',nodes:[],edges:[],cables:structuredClone(defaults)});
let model=blank(), selected=new Set(), selectedEdge=null, view={x:50,y:50,z:1}, mode='select', source=null, pending=null, space=false, gesture=null, history=[], future=[], saveTimer;
const canvas=$('#canvas'),world=$('#world');
const nodeBy=id=>model.nodes.find(n=>n.id===id), portBy=(id,p)=>nodeBy(id)?.ports.find(x=>x.id===p), used=(id,p,except)=>model.edges.some(e=>e.id!==except&&((e.from===id&&e.fromPort===p)||(e.to===id&&e.toPort===p)));
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function checkpoint(){history.push(JSON.stringify(model));if(history.length>80)history.shift();future=[]}
function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('netsketch-draft-v1',JSON.stringify(model));$('#saveStatus').textContent='● 草稿已自动保存'}catch{$('#saveStatus').textContent='草稿保存失败，请保存到本地文件'}},250)}
function changed(inspect=true){render();if(inspect)renderInspector();persist()}
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(JSON.stringify(model));model=JSON.parse(from.pop());selected.clear();selectedEdge=null;source=null;changed()}
function ports(count,prefix='GE1/0/',kind='RJ45'){return Array.from({length:count},(_,i)=>({id:uid(),name:prefix+(i+1),kind}))}
function defaultPorts(type){const named=(names,kind)=>names.map(name=>({id:uid(),name,kind}));switch(type){case 'region':case 'text':return [];case 'switch':return ports(24).concat(ports(4,'SFP1/0/','SFP'));case 'ont':return named(['PON'],'PON').concat(ports(4,'LAN'));case 'patchpanel':return ports(24,'PORT');case 'converter':return ports(1,'LAN').concat(ports(1,'OPT','SFP'));case 'behavior':case 'firewall':case 'vpn':case 'router':return ports(4,'GE');case 'loadbalancer':return ports(4,'GE').concat(ports(2,'SFP','SFP+'));case 'ac':return ports(2,'GE').concat(ports(2,'SFP','SFP'));case 'server':case 'nas':case 'nvr':return ports(2,'ETH');case 'ups':return named(['MGMT'],'RJ45');default:return ports(1,'ETH')}}
function makeNode(type,x,y){return{id:uid(),type,name:types[type][0]+' '+(model.nodes.filter(n=>n.type===type).length+1),brand:'',model:'',...assetDefaults(),...(type==='region'?{width:320,height:240,color:'#dbeafe'}:{}),x,y,expanded:false,ports:defaultPorts(type)}}
function addNode(type,x,y){checkpoint();const n=makeNode(type,snapGrid(x),snapGrid(y));model.nodes.push(n);mode='select';source=null;selected=new Set([n.id]);selectedEdge=null;changed()}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-view.x)/view.z,y:(e.clientY-r.top-view.y)/view.z}}
function managementIpLines(n){const value=(n.managementIp||'').trim();if(!value)return [];return value.split(/\r?\n/).flatMap(part=>{const chars=Array.from(part),lines=[];for(let i=0;i<chars.length;i+=21)lines.push(chars.slice(i,i+21).join(''));return lines.length?lines:['']})}
function managementIpHeight(n){return Math.max(0,managementIpLines(n).length-1)*14}
function isAnnotation(n){return n.type==='text'||n.type==='region'}
function nodeWidth(n){return isAnnotation(n)?n.width||(n.type==='region'?320:160):160}
function textLines(n){return n.name.split('\n').flatMap(part=>{let lines=[],line='',width=0;for(const c of part){const size=c.charCodeAt(0)>255?2:1;if(width+size>Math.max(4,Math.floor((nodeWidth(n)-26)/6))){lines.push(line);line='';width=0}line+=c;width+=size}return [...lines,line]})}
function nodeHeight(n){if(n.type==='region')return n.height||240;if(n.type==='text')return n.height||Math.max(60,Math.ceil((textLines(n).length*18+28)/20)*20);return Math.ceil(((n.expanded?151:76)+managementIpHeight(n))/20)*20}
function resizeHandles(){return ['nw','ne','sw','se'].map(dir=>`<span class="resize-handle ${dir}" data-resize="${dir}" title="拖动调整大小"></span>`).join('')}
function textNodeMarkup(n){return `<div class="node text-node ${selected.has(n.id)?'selected':''}" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px;width:${nodeWidth(n)}px;height:${nodeHeight(n)}px"><div class="annotation-content">${textLines(n).map(line=>`<div>${esc(line)||'&nbsp;'}</div>`).join('')}</div>${resizeHandles()}</div>`}
function regionMarkup(n){return `<div class="node region-node ${selected.has(n.id)?'selected':''}" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px;width:${nodeWidth(n)}px;height:${nodeHeight(n)}px;background:${n.color||'#dbeafe'}66;border-color:${n.color||'#dbeafe'}"><div class="region-title">${esc(n.name)}</div>${resizeHandles()}</div>`}
function regionSvg(n){return `<g transform="translate(${n.x},${n.y})"><rect width="${nodeWidth(n)}" height="${nodeHeight(n)}" rx="11" fill="${n.color||'#dbeafe'}" fill-opacity="0.4" stroke="${n.color||'#dbeafe'}"/><svg x="12" y="8" width="${nodeWidth(n)-24}" height="22" overflow="hidden"><text y="15" font-size="12" fill="#40516b">${esc(n.name)}</text></svg></g>`}
function textNodeSvg(n){return `<svg x="${n.x}" y="${n.y}" width="${nodeWidth(n)}" height="${nodeHeight(n)}" overflow="hidden">${textLines(n).map((line,i)=>`<text x="12" y="${27+i*18}" font-size="12" fill="#40516b">${esc(line)}</text>`).join('')}</svg>`}
function refreshSelection(){document.querySelectorAll('[data-node]').forEach(el=>el.classList.toggle('selected',selected.has(el.dataset.node)));renderEdges();$('#copy').disabled=!selected.size;$('#delete').disabled=!selected.size&&!selectedEdge}
function connectionOffset(n,other,edge,horizontal){const cx=n.x+80,cy=n.y+nodeHeight(n)/2,sign=Math.sign(horizontal?other.x-n.x:other.y+nodeHeight(other)/2-cy);const peers=model.edges.filter(e=>e.from===n.id||e.to===n.id).filter(e=>{const o=nodeBy(e.from===n.id?e.to:e.from),dx=o.x+80-cx,dy=o.y+nodeHeight(o)/2-cy;return (Math.abs(dx)>Math.abs(dy))===horizontal&&Math.sign(horizontal?dx:dy)===sign});return (peers.findIndex(e=>e.id===edge.id)-(peers.length-1)/2)*Math.min(32,(horizontal?nodeHeight(n)-24:136)/Math.max(1,peers.length))}
function route(e){const a=nodeBy(e.from),b=nodeBy(e.to),ac={x:a.x+80,y:a.y+nodeHeight(a)/2},bc={x:b.x+80,y:b.y+nodeHeight(b)/2};const horizontal=Math.abs(bc.x-ac.x)>Math.abs(bc.y-ac.y);if(horizontal){ac.y+=connectionOffset(a,b,e,true);bc.y+=connectionOffset(b,a,e,true)}else{ac.x+=connectionOffset(a,b,e,false);bc.x+=connectionOffset(b,a,e,false)}let p,q,d,l1,l2;
 if(horizontal){const dir=bc.x>=ac.x?1:-1;p={x:ac.x+80*dir,y:ac.y};q={x:bc.x-80*dir,y:bc.y};const mid=(p.x+q.x)/2;d=`M${p.x},${p.y} H${mid} V${q.y} H${q.x}`;l1={x:p.x+8*dir,y:p.y-9,anchor:dir>0?'start':'end'};l2={x:q.x-8*dir,y:q.y-9,anchor:dir>0?'end':'start'};
 }else{const dir=bc.y>=ac.y?1:-1;p={x:ac.x,y:ac.y+nodeHeight(a)/2*dir};q={x:bc.x,y:bc.y-nodeHeight(b)/2*dir};const mid=(p.y+q.y)/2;d=`M${p.x},${p.y} V${mid} H${q.x} V${q.y}`;l1={x:p.x+9,y:p.y+17*dir,anchor:'start'};l2={x:q.x+9,y:q.y-11*dir,anchor:'start'}}return{d,p,q,l1,l2}}
function endpointLayout(){
 const measure=endpointLayout.measure||(endpointLayout.measure=document.createElement('canvas').getContext('2d'));measure.font='11px "Segoe UI", "Microsoft YaHei", sans-serif';
 const labels=model.edges.flatMap(e=>{const r=route(e),color=model.cables.find(c=>c.id===e.cable).color;return [[e.from,e.fromPort,r.p],[e.to,e.toPort,r.q]].map(([id,port,point])=>{const n=nodeBy(id),name=portBy(id,port).name;const normal=Math.abs(point.x-n.x)<.01?{x:-1,y:0}:Math.abs(point.x-n.x-160)<.01?{x:1,y:0}:Math.abs(point.y-n.y)<.01?{x:0,y:-1}:{x:0,y:1};return{edgeId:e.id,name,point,normal,color,w:Math.ceil(measure.measureText(name).width)+16,h:22}})});
 for(const e of model.edges){if(!e.showBandwidth||!e.bandwidth?.trim())continue;const r=route(e),a=nodeBy(e.from),b=nodeBy(e.to),horizontal=Math.abs((b.x+80)-(a.x+80))>Math.abs((b.y+nodeHeight(b)/2)-(a.y+nodeHeight(a)/2));const name=e.bandwidth.trim();labels.push({edgeId:e.id,kind:'bandwidth',name,point:{x:(r.p.x+r.q.x)/2,y:(r.p.y+r.q.y)/2},normal:horizontal?{x:0,y:-1}:{x:1,y:0},color:model.cables.find(c=>c.id===e.cable).color,w:Math.ceil(measure.measureText(name).width)+16,h:22})}
 // Keep equal clearance above and below the card. Reserve the small port-count
 // badge separately instead of expanding the entire bottom edge of the device.
 return EndpointLabels.layout(labels,model.nodes.filter(n=>n.type!=='region').flatMap(n=>[
  {x:n.x-5,y:n.y-5,w:nodeWidth(n)+10,h:nodeHeight(n)+10},
  {x:n.x+54,y:n.y+nodeHeight(n)-9,w:52,h:16}
 ]));
}
function labelMarkup(labels){return labels.map(l=>`<g data-edge="${l.edgeId}" class="endpoint-label ${l.kind==='bandwidth'?'bandwidth-label':''}" style="cursor:pointer"><path d="M${l.point.x},${l.point.y} L${l.target.x},${l.target.y}" fill="none" stroke="${l.color}" stroke-width="1" opacity="0.7" pointer-events="none"/><rect x="${l.x}" y="${l.y}" width="${l.w}" height="${l.h}" rx="4" fill="#ffffff" stroke="${l.color}" stroke-opacity="0.45"/><text x="${l.x+8}" y="${l.y+15}" font-family="Segoe UI,Microsoft YaHei,sans-serif" font-size="11" fill="#40516b" pointer-events="none">${esc(l.name)}</text></g>`).join('')}
function renderEdges(){ $('#edges').innerHTML=model.edges.map(e=>{const r=route(e),c=model.cables.find(c=>c.id===e.cable);return `<g data-edge="${e.id}"><path class="edge-line ${selectedEdge===e.id?'edge-selected':''}" stroke="${c.color}" d="${r.d}"/><path class="edge-hit" d="${r.d}"/><circle cx="${r.p.x}" cy="${r.p.y}" r="3.5" fill="${c.color}"/><circle cx="${r.q.x}" cy="${r.q.y}" r="3.5" fill="${c.color}"/></g>`}).join('')+labelMarkup(endpointLayout())}
function transform(){world.style.transform=`translate(${view.x}px,${view.y}px) scale(${view.z})`;canvas.style.backgroundSize=`${20*view.z}px ${20*view.z}px`;canvas.style.backgroundPosition=`${view.x-10*view.z}px ${view.y-10*view.z}px`;$('#zoomValue').textContent=Math.round(view.z*100)+'%'}
function render(){ $('#projectName').value=model.name;$('#counts').textContent=`${model.nodes.filter(n=>!isAnnotation(n)).length} 台设备 · ${model.nodes.filter(n=>n.type==='text').length} 个文本 · ${model.nodes.filter(n=>n.type==='region').length} 个区域 · ${model.edges.length} 条连接`;$('#empty').style.display=model.nodes.length?'none':'block';$('#regions').innerHTML=model.nodes.filter(n=>n.type==='region').map(regionMarkup).join('');$('#nodes').innerHTML=model.nodes.filter(n=>n.type!=='region').map(n=>n.type==='text'?textNodeMarkup(n):`<div class="node ${selected.has(n.id)?'selected':''} ${source===n.id?'connect-source':''}" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px;height:${nodeHeight(n)}px"><div class="node-main"><div class="device-icon">${icon(n.type)}</div><div><div class="node-name" title="${esc(n.name)}">${esc(n.name)}</div><div class="node-type">${types[n.type][1]}</div></div></div>${managementIpLines(n).length?`<div class="node-ip" title="管理 IP：${esc(n.managementIp)}">${managementIpLines(n).map(line=>`<span>${esc(line)||'&nbsp;'}</span>`).join('')}</div>`:''}${n.expanded?`<div class="node-details">类型：${types[n.type][0]}<br>品牌：${esc(n.brand||'未设置')}<br>型号：${esc(n.model||'未设置')}</div>`:''}<span class="node-badge">${n.ports.filter(p=>used(n.id,p.id)).length} / ${n.ports.length}</span></div>`).join('');renderEdges();$('#legend').innerHTML=model.cables.map(c=>`<span class="legend-item"><i class="swatch" style="background:${c.color}"></i>${esc(c.name)}</span>`).join('');$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;$('#copy').disabled=!selected.size;$('#delete').disabled=!selected.size&&!selectedEdge;$('#selectTool').classList.toggle('active',mode==='select');$('#connectTool').classList.toggle('active',mode==='connect');$('#modeNotice').style.display=mode==='connect'?'block':'none';$('#modeNotice').textContent=source?'点击目标设备，选择两端端口':'点击第一台设备开始连线 · Esc 退出';transform()}
function field(label,key,value,type='text',max=120){return `<label>${label}<input data-field="${key}" type="${type}" value="${esc(value)}" maxlength="${max}"></label>`}
function assetDefaults(){return {purpose:'',managementIp:'',serialNumber:'',managementProtocol:'',managementPort:'',physicalLocation:'',owner:'',supplier:'',rackDate:'',warranty:'',warrantyUntil:'',notes:''}}
function assetFields(n){const longField=(label,key)=>`<label>${label}<textarea data-field="${key}" maxlength="2000" rows="3">${esc(n[key])}</textarea></label>`;return field('序列号','serialNumber',n.serialNumber)+`<details class="asset-group"><summary>管理连接</summary>`+`<label>管理IP地址<textarea data-field="managementIp" rows="3" maxlength="120" placeholder="每行填写一个 IP 地址">${esc(n.managementIp)}</textarea></label>`+`<label>管理协议<input data-field="managementProtocol" value="${esc(n.managementProtocol)}" maxlength="120" list="managementProtocols" placeholder="如 HTTPS、SSH、SNMP"><datalist id="managementProtocols"><option value="HTTPS"><option value="HTTP"><option value="SSH"><option value="Telnet"><option value="SNMP"><option value="RDP"></datalist></label>`+field('端口（管理服务）','managementPort',n.managementPort)+`<p class="tip">可填写多个协议及对应端口，如 HTTPS:443、SSH:22。物理接口在下方端口管理中维护。</p></details><details class="asset-group"><summary>位置与归属</summary>`+field('物理位置','physicalLocation',n.physicalLocation)+field('设备归属','owner',n.owner)+field('供应商','supplier',n.supplier)+`</details><details class="asset-group"><summary>上架与保修</summary>`+field('上架时间','rackDate',n.rackDate,'date')+longField('保修信息','warranty')+field('保修期至','warrantyUntil',n.warrantyUntil,'date')+`</details>`+longField('备注','notes')}
function options(current){return ['RJ45','PON','SFP','SFP+','QSFP','QSFP+','USB','其他'].map(t=>`<option ${t===current?'selected':''}>${t}</option>`).join('')}
function renderInspector(){const body=$('#inspectorBody');if(selectedEdge){const e=model.edges.find(e=>e.id===selectedEdge);$('#inspectorTitle').textContent='线路属性';body.innerHTML=`<div class="edge-summary">${esc(nodeBy(e.from).name)} <small>/ ${esc(portBy(e.from,e.fromPort).name)}</small><br>↕<br>${esc(nodeBy(e.to).name)} <small>/ ${esc(portBy(e.to,e.toPort).name)}</small></div><label>线材类型<select id="edgeCable">${model.cables.map(c=>`<option value="${c.id}" ${c.id===e.cable?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>带宽<input id="edgeBandwidth" list="bandwidthOptions" maxlength="80" placeholder="如 1 Gbps，可自定义" value="${esc(e.bandwidth || '')}"></label><label><input type="checkbox" id="edgeShowBandwidth" ${e.showBandwidth?'checked':''}>在主图显示带宽</label><label>此类线材颜色<input id="cableColor" type="color" value="${model.cables.find(c=>c.id===e.cable).color}"></label><p class="tip">颜色修改将应用于项目内所有同类线材。</p><button class="wide" id="reconnect">更换两端端口</button><button class="danger" id="removeEdge">删除线路</button>`;$('#edgeShowBandwidth').onchange=ev=>{checkpoint();e.showBandwidth=ev.target.checked;changed(false)};$('#edgeBandwidth').onchange=ev=>{checkpoint();e.bandwidth=ev.target.value.trim();changed(false)};$('#edgeCable').onchange=ev=>{checkpoint();e.cable=ev.target.value;changed()};$('#cableColor').onchange=ev=>{checkpoint();model.cables.find(c=>c.id===e.cable).color=ev.target.value;changed()};$('#removeEdge').onclick=removeSelection;$('#reconnect').onclick=()=>openConnection(e.from,e.to,e);return}
 if(selected.size!==1){$('#inspectorTitle').textContent='属性面板';body.innerHTML=`<div class="inspector-empty"><div class="large">▧</div>${selected.size?`已选择 ${selected.size} 台设备<br>拖动可一起移动，Delete 删除`:'选择设备或线路<br>在这里查看并编辑属性'}</div><div class="section-title">画布快捷操作</div><p class="tip">V　选择工具<br>C　连接设备<br>Shift + 点击　多选设备<br>空白处拖动　框选设备<br>空格 + 拖动 / 中键　平移画布<br>Ctrl + Z　撤销操作<br>Ctrl + S　保存本地项目<br>双击设备　展开 / 收起详情</p>`;return}
 const n=nodeBy([...selected][0]);if(isAnnotation(n)){$('#inspectorTitle').textContent=n.type==='region'?'区域框':'文本框';body.innerHTML=`<label>文本内容<textarea id="textContent" rows="7" maxlength="120">${esc(n.name)}</textarea></label>${n.type==='region'?`<label>背景颜色<input id="regionColor" type="color" value="${n.color||'#dbeafe'}"></label>`:''}<div class="row"><label>宽度<input id="annotationWidth" type="number" min="80" max="4000" step="20" value="${nodeWidth(n)}"></label><label>高度<input id="annotationHeight" type="number" min="60" max="4000" step="20" value="${nodeHeight(n)}"></label></div><p class="tip">拖动四角调节大小，拖动框内移动。尺寸吸附到网格。</p><button class="danger" id="removeText">删除${n.type==='region'?'区域框':'文本框'}</button>`;$('#textContent').onchange=ev=>{checkpoint();n.name=ev.target.value;changed(false)};for(const [id,key,min] of [['annotationWidth','width',80],['annotationHeight','height',60]])$('#'+id).onchange=ev=>{const value=Number(ev.target.value);if(!Number.isFinite(value)||value<min||value>4000){renderInspector();return}checkpoint();n[key]=Math.max(min,snapGrid(value));changed(false)};if(n.type==='region')$('#regionColor').onchange=ev=>{checkpoint();n.color=ev.target.value;changed(false)};$('#removeText').onclick=removeSelection;return}$('#inspectorTitle').textContent='设备属性';body.innerHTML=field('设备名称','name',n.name)+field('设备用途','purpose',n.purpose)+`<label>设备类型<select data-field="type">${Object.entries(types).filter(([k])=>!['text','region'].includes(k)).map(([k,v])=>`<option value="${k}" ${k===n.type?'selected':''}>${v[0]}</option>`).join('')}</select></label>`+field('品牌','brand',n.brand)+field('型号','model',n.model)+assetFields(n)+`<label><input type="checkbox" id="expanded" ${n.expanded?'checked':''}>在画布上展开设备详情</label><div class="section-title">端口管理 <span id="portSummary">${n.ports.filter(p=>used(n.id,p.id)).length} 已连接 / ${n.ports.length} 总数</span></div><div class="port-builder"><div class="row"><label>前缀<input id="portPrefix" value="GE1/0/" maxlength="30"></label><label>起始号<input id="portStart" type="number" value="1" min="0" max="9999"></label></div><div class="row"><label>数量<input id="portCount" type="number" value="4" min="1" max="128"></label><label>接口类型<select id="portKind">${options('RJ45')}</select></label></div><button id="addPorts">＋ 批量添加端口</button></div><div class="port-tools"><label>端口排序<select id="portSort"><option value="">选择排序方式</option><option value="asc">名称升序（1、2、10）</option><option value="desc">名称降序</option><option value="kind">接口类型，再按名称</option><option value="used">已连接优先</option></select></label><button id="removeIdlePorts" type="button">一键删除空闲口</button></div><div class="port-list">${portRows(n)}</div><button id="removeNode" class="danger">删除设备</button>`;
 body.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>{if(el.dataset.field==='name'&&!el.value.trim()){toast('设备名称不能为空');renderInspector();return}checkpoint();n[el.dataset.field]=el.value.trim();changed(false)});$('#expanded').onchange=ev=>{checkpoint();n.expanded=ev.target.checked;changed(false)};$('#removeNode').onclick=removeSelection;
 $('#addPorts').onclick=()=>{const prefix=$('#portPrefix').value,start=Number($('#portStart').value),count=Number($('#portCount').value),kind=$('#portKind').value;if(!Number.isInteger(start)||start<0||start>9999||!Number.isInteger(count)||count<1||count>128||n.ports.length+count>512){toast('起始号 0–9999，单次 1–128 个，设备最多 512 个端口');return}const names=Array.from({length:count},(_,i)=>prefix+(start+i));if(names.some(name=>n.ports.some(p=>p.name===name))){toast('端口名称重复，请修改前缀或起始号');return}checkpoint();n.ports.push(...names.map(name=>({id:uid(),name,kind})));refreshPorts(n);toast(`已添加 ${count} 个端口`)};
 bindPortRows(n);
 $('#portSort').onchange=ev=>{const method=ev.target.value;if(!method)return;const sorted=sortPorts(n.ports,method,p=>used(n.id,p.id));if(sorted.some((p,i)=>p.id!==n.ports[i].id)){checkpoint();n.ports=sorted;refreshPorts(n)}ev.target.value=''};
 $('#removeIdlePorts').onclick=()=>{const keep=n.ports.filter(p=>used(n.id,p.id)),count=n.ports.length-keep.length;if(!count)return;checkpoint();n.ports=keep;refreshPorts(n);toast('已删除 '+count+' 个空闲端口，可撤销')};
 $('#removeIdlePorts').disabled=n.ports.every(p=>used(n.id,p.id));
}

function sortPorts(ports,method,isUsed){const name=(a,b)=>a.name.localeCompare(b.name,'zh-CN',{numeric:true,sensitivity:'base'});return [...ports].sort((a,b)=>method==='desc'?name(b,a):method==='kind'?a.kind.localeCompare(b.kind)||name(a,b):method==='used'?Number(isUsed(b))-Number(isUsed(a))||name(a,b):name(a,b))}
function portRows(n){return n.ports.map((p,i)=>`<div class="port-row" data-port="${p.id}"><input aria-label="端口名称" value="${esc(p.name)}" maxlength="40"><select aria-label="接口类型">${options(p.kind)}</select><span class="port-state ${used(n.id,p.id)?'used':''}">${used(n.id,p.id)?'● 已连接':'○ 空闲'}</span><div class="port-actions"><button type="button" data-step="-1" title="上移端口" ${i===0?'disabled':''}>↑</button><button type="button" data-step="1" title="下移端口" ${i===n.ports.length-1?'disabled':''}>↓</button><button type="button" data-remove title="删除空闲端口" ${used(n.id,p.id)?'disabled':''}>×</button></div></div>`).join('')}
function refreshPorts(n){const list=$('.port-list'),scroll=list.scrollTop,panel=$('.inspector'),panelScroll=panel.scrollTop;list.innerHTML=portRows(n);$('#portSummary').textContent=n.ports.filter(p=>used(n.id,p.id)).length+' 已连接 / '+n.ports.length+' 总数';$('#removeIdlePorts').disabled=n.ports.every(p=>used(n.id,p.id));bindPortRows(n);list.scrollTop=scroll;panel.scrollTop=panelScroll;changed(false)}
function bindPortRows(n){document.querySelectorAll('[data-port]').forEach(row=>{const p=n.ports.find(p=>p.id===row.dataset.port);row.querySelector('input').onchange=ev=>{const name=ev.target.value.trim();if(!name||n.ports.some(q=>q.id!==p.id&&q.name===name)){toast('端口名称不能为空或重复');ev.target.value=p.name;return}checkpoint();p.name=name;changed(false)};row.querySelector('select').onchange=ev=>{checkpoint();p.kind=ev.target.value;changed(false)};row.querySelector('[data-remove]').onclick=()=>{if(used(n.id,p.id))return;checkpoint();n.ports=n.ports.filter(q=>q.id!==p.id);refreshPorts(n)};row.querySelectorAll('[data-step]').forEach(button=>button.onclick=()=>{const i=n.ports.findIndex(q=>q.id===p.id),j=i+Number(button.dataset.step);if(j<0||j>=n.ports.length)return;checkpoint();[n.ports[i],n.ports[j]]=[n.ports[j],n.ports[i]];refreshPorts(n)})})}

function duplicateNodes(nodes){return nodes.map(n=>({...structuredClone(n),id:uid(),x:n.x+20,y:n.y+20,ports:n.ports.map(p=>({...p,id:uid()}))}))}
function copySelection(){const originals=model.nodes.filter(n=>selected.has(n.id));if(!originals.length)return;checkpoint();const copies=duplicateNodes(originals);model.nodes.push(...copies);selected=new Set(copies.map(n=>n.id));selectedEdge=null;source=null;mode='select';changed();toast('已复制 '+copies.length+' 个对象')}
function removeSelection(){if(!selected.size&&!selectedEdge)return;checkpoint();model.edges=model.edges.filter(e=>e.id!==selectedEdge&&!selected.has(e.from)&&!selected.has(e.to));model.nodes=model.nodes.filter(n=>!selected.has(n.id));selected.clear();selectedEdge=null;source=null;changed()}
function setMode(m){mode=m;source=null;render()}
function openConnection(a,b,existing=null){pending={a,b,existing:existing?.id};$('#connectionFields').innerHTML=[['from',a,existing?.fromPort],['to',b,existing?.toPort]].map(([key,id,current])=>`<label>${key==='from'?'起点':'终点'} · ${esc(nodeBy(id).name)}<select id="${key}Port" required>${nodeBy(id).ports.map(p=>`<option value="${p.id}" ${used(id,p.id,existing?.id)?'disabled':''} ${current===p.id?'selected':''}>${esc(p.name)} · ${p.kind}${used(id,p.id,existing?.id)?'（已占用）':''}</option>`).join('')}</select></label>`).join('');$('#connectionCable').innerHTML=model.cables.map(c=>`<option value="${c.id}" ${c.id===existing?.cable?'selected':''}>${esc(c.name)}</option>`).join('');$('#connectionBandwidth').value=existing?.bandwidth||'';$('#connectionShowBandwidth').checked=!!existing?.showBandwidth;$('#connectionDialog').showModal()}
$('#connectionForm').onsubmit=ev=>{ev.preventDefault();const fp=$('#fromPort').value,tp=$('#toPort').value;if(!fp||!tp||used(pending.a,fp,pending.existing)||used(pending.b,tp,pending.existing)){toast('请选择两端空闲端口');return}checkpoint();const e={id:pending.existing||uid(),from:pending.a,to:pending.b,fromPort:fp,toPort:tp,cable:$('#connectionCable').value,bandwidth:$('#connectionBandwidth').value.trim(),showBandwidth:$('#connectionShowBandwidth').checked};if(pending.existing)model.edges=model.edges.filter(e=>e.id!==pending.existing);model.edges.push(e);selected.clear();selectedEdge=e.id;source=null;$('#connectionDialog').close();changed();toast('端口连接已建立')};$('#cancelConnection').onclick=()=>$('#connectionDialog').close();$('#connectionDialog').onclose=()=>{source=null;render()};
function renderLibrary(query=''){const q=query.trim().toLowerCase();let count=0;$('#deviceLibrary').innerHTML=categories.map(([label,keys])=>{const matches=keys.filter(k=>`${types[k][0]} ${types[k][1]} ${k}`.toLowerCase().includes(q));count+=matches.length;return matches.length?`<div class="category-label">${label}</div>`+matches.map(k=>{const v=types[k];return `<div class="device-item" draggable="true" data-type="${k}" title="拖入画布或双击添加"><div class="device-icon">${icon(k)}</div><div><strong>${v[0]}</strong><small>${v[1]}</small></div><span class="grip">⠿</span></div>`}).join(''):''}).join('')||'<p class="tip">没有匹配设备，可搜索“通用设备”自定义。</p>';$('#libraryCount').textContent=count;bindLibrary()}
renderLibrary();$('#deviceSearch').oninput=e=>renderLibrary(e.target.value);
function bindLibrary(){document.querySelectorAll('.device-item').forEach(el=>{el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.type);el.ondblclick=()=>addNode(el.dataset.type,(canvas.clientWidth/2-view.x)/view.z-80,(canvas.clientHeight/2-view.y)/view.z-42)});} bindLibrary();canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();const t=e.dataTransfer.getData('text/plain');if(!types[t])return;const p=point(e);addNode(t,p.x-80,p.y-42)};
canvas.onpointerdown=e=>{if(e.target.closest('button,input,select,textarea,a,.legend,.zoom-control')||e.button===2)return;const n=e.target.closest('[data-node]'),edge=e.target.closest('[data-edge]');canvas.focus();if(space||e.button===1){e.preventDefault();gesture={type:'pan',cx:e.clientX,cy:e.clientY,x:view.x,y:view.y}}else if(n){const id=n.dataset.node;if(e.target.closest('[data-resize]')&&isAnnotation(nodeBy(id))){e.preventDefault();selected=new Set([id]);selectedEdge=null;mode='select';source=null;const device=nodeBy(id);gesture={type:'resize',id,dir:e.target.closest('[data-resize]').dataset.resize,p:point(e),x:device.x,y:device.y,w:nodeWidth(device),h:nodeHeight(device),moved:false};refreshSelection();renderInspector();canvas.setPointerCapture(e.pointerId);return}if(mode==='connect'&&!isAnnotation(nodeBy(id))){const device=nodeBy(id);gesture={type:'connect-node',id,p:point(e),positions:[{id,x:device.x,y:device.y}],moved:false};canvas.setPointerCapture(e.pointerId);return}if(isAnnotation(nodeBy(id))){mode='select';source=null}if(e.shiftKey){if(selected.has(id))selected.delete(id);else selected.add(id)}else if(!selected.has(id))selected=new Set([id]);selectedEdge=null;const p=point(e);gesture={type:'nodes',p,positions:[...selected].map(id=>({id,x:nodeBy(id).x,y:nodeBy(id).y})),moved:false};refreshSelection();renderInspector()}else if(edge){selected.clear();selectedEdge=edge.dataset.edge;render();renderInspector();return}else{if(!e.shiftKey)selected.clear();selectedEdge=null;const p=point(e);gesture={type:'box',p,base:new Set(selected)};render();renderInspector()}canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(!gesture)return;const g=gesture,p=point(e);if(g.type==='pan'){view.x=g.x+e.clientX-g.cx;view.y=g.y+e.clientY-g.cy;transform()}else if(g.type==='resize'){const dx=p.x-g.p.x,dy=p.y-g.p.y;if(!g.moved&&Math.hypot(dx,dy)*view.z<4)return;if(!g.moved){checkpoint();g.moved=true}Object.assign(nodeBy(g.id),resizeBox(g,dx,dy));render()}else if(g.type==='nodes'||g.type==='connect-node'){const dx=p.x-g.p.x,dy=p.y-g.p.y;if(!g.moved&&Math.hypot(dx,dy)*view.z<4)return;if(!g.moved){checkpoint();g.moved=true;if(g.type==='connect-node'){mode='select';source=null;selected=new Set([g.id]);selectedEdge=null}}moveDevices(g,dx,dy)}else{const x=Math.min(p.x,g.p.x),y=Math.min(p.y,g.p.y),w=Math.abs(p.x-g.p.x),h=Math.abs(p.y-g.p.y);Object.assign($('#marquee').style,{display:'block',left:x*view.z+view.x+'px',top:y*view.z+view.y+'px',width:w*view.z+'px',height:h*view.z+'px'});selected=new Set(g.base);model.nodes.filter(n=>n.x<x+w&&n.x+nodeWidth(n)>x&&n.y<y+h&&n.y+nodeHeight(n)>y).forEach(n=>selected.add(n.id));render()}};
function snapGrid(value){return Math.round(value/20)*20}
function resizeBox(g,dx,dy){const west=g.dir.includes('w'),north=g.dir.includes('n'),width=Math.max(80,Math.min(4000,snapGrid(g.w+(west?-dx:dx)))),height=Math.max(60,Math.min(4000,snapGrid(g.h+(north?-dy:dy))));return {x:west?g.x+g.w-width:g.x,y:north?g.y+g.h-height:g.y,width,height}}
function moveDevices(g,dx,dy){let moved=false;g.positions.forEach(p=>{const n=nodeBy(p.id),x=snapGrid(p.x+dx),y=snapGrid(p.y+dy);if(n.x!==x||n.y!==y)moved=true;n.x=x;n.y=y});if(moved||!g.gridRendered){render();g.gridRendered=true}}
function endGesture(e){const g=gesture;if(!g)return;gesture=null;if(g?.moved)persist();if(g?.type==='connect-node'&&!g.moved&&e?.type!=='pointercancel'){if(!source){source=g.id;render()}else if(source!==g.id)openConnection(source,g.id);else toast('请选择另一台设备')}$('#marquee').style.display='none';renderInspector()}canvas.onpointerup=endGesture;canvas.onpointercancel=endGesture;
canvas.ondblclick=e=>{const n=nodeBy(e.target.closest('[data-node]')?.dataset.node);if(n&&!isAnnotation(n)&&mode==='select'){checkpoint();n.expanded=!n.expanded;changed()}};
function zoom(factor,cx=canvas.clientWidth/2,cy=canvas.clientHeight/2){const z=Math.max(.25,Math.min(2.5,view.z*factor));view.x=cx-(cx-view.x)*z/view.z;view.y=cy-(cy-view.y)*z/view.z;view.z=z;transform()}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)},{passive:false});
function diagramBounds(labels=endpointLayout()){const boxes=model.nodes.map(n=>({x:n.x,y:n.y,w:nodeWidth(n),h:nodeHeight(n)+10})).concat(labels);const x=Math.min(...boxes.map(b=>b.x)),y=Math.min(...boxes.map(b=>b.y));return{x,y,w:Math.max(...boxes.map(b=>b.x+b.w))-x,h:Math.max(...boxes.map(b=>b.y+b.h))-y}}
function fit(){if(!model.nodes.length){view={x:50,y:50,z:1};transform();return}const b=diagramBounds(),minX=b.x-60,minY=b.y-60,maxX=b.x+b.w+60,maxY=b.y+b.h+100;const z=Math.max(.25,Math.min(1.3,canvas.clientWidth/(maxX-minX),canvas.clientHeight/(maxY-minY)));view={z,x:(canvas.clientWidth-(maxX-minX)*z)/2-minX*z,y:(canvas.clientHeight-(maxY-minY)*z)/2-minY*z};transform()}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const filename=()=>model.name.replace(/[\\/:*?"<>|]/g,'_')||'网络拓扑';
function save(){download(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),filename()+'.netsketch.json');toast('项目文件已导出到浏览器下载目录')}
function validate(data){if(!data||data.version!==1||typeof data.name!=='string'||!Array.isArray(data.nodes)||!Array.isArray(data.edges)||!Array.isArray(data.cables)||data.nodes.length>2000||data.edges.length>10000||!data.cables.length)throw Error('项目格式无效或版本不受支持');const ids=new Set(),take=id=>{if(typeof id!=='string'||!/^[a-zA-Z0-9_-]{1,80}$/.test(id)||ids.has(id))throw Error('项目标识无效或重复');ids.add(id)},str=(v,max=120)=>{if(typeof v!=='string'||v.length>max)throw Error('项目文本格式无效');return v};data.cables.forEach(c=>{take(c.id);str(c.name);if(!/^#[0-9a-f]{6}$/i.test(c.color))throw Error('线材颜色无效')});data.nodes.forEach(n=>{take(n.id);if(!Object.hasOwn(types,n.type)||!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>1e6||Math.abs(n.y)>1e6||!Array.isArray(n.ports)||n.ports.length>512)throw Error('设备数据无效');str(n.name);str(n.brand);str(n.model);if(['text','region'].includes(n.type)){for(const [key,min] of [['width',80],['height',60]])if(n[key]!==undefined&&(!Number.isFinite(n[key])||n[key]<min||n[key]>4000))throw Error('标注尺寸无效');if(n.type==='region'){if(n.color===undefined)n.color='#dbeafe';if(!/^#[0-9a-f]{6}$/i.test(n.color))throw Error('区域颜色无效')}if(n.ports.length)throw Error('标注不能包含端口')}for(const key of Object.keys(assetDefaults())){if(n[key]===undefined)n[key]='';str(n[key],['notes','warranty'].includes(key)?2000:120)}n.expanded=!!n.expanded;const names=new Set();n.ports.forEach(p=>{take(p.id);str(p.name,40);if(!p.name.trim()||names.has(p.name)||!['RJ45','PON','SFP','SFP+','QSFP','QSFP+','USB','其他'].includes(p.kind))throw Error('端口数据无效');names.add(p.name)})});const occupied=new Set();data.edges.forEach(e=>{take(e.id);if(e.bandwidth===undefined)e.bandwidth='';str(e.bandwidth,80);if(e.showBandwidth===undefined)e.showBandwidth=false;if(typeof e.showBandwidth!=='boolean')throw Error('带宽显示设置无效');if(e.from===e.to||!data.cables.some(c=>c.id===e.cable))throw Error('连接数据无效');for(const [id,p] of [[e.from,e.fromPort],[e.to,e.toPort]]){if(!data.nodes.find(n=>n.id===id)?.ports.some(q=>q.id===p)||occupied.has(p))throw Error('连接端口缺失或重复占用');occupied.add(p)}});return data}
$('#fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>15000000)throw Error('项目文件不能超过 15 MB');const data=validate(JSON.parse(await f.text()));checkpoint();model=data;selected.clear();selectedEdge=null;source=null;changed();fit();toast('项目已打开，可撤销恢复原项目')}catch(err){toast('打开失败：'+err.message)}e.target.value=''};
function demo(){checkpoint();model=blank();model.name='办公室网络拓扑';const spec=[['cloud','互联网',340,15,'运营商','Internet'],['firewall','出口防火墙',340,190,'Fortinet','FortiGate 60F'],['switch','核心交换机',340,365,'华为','S5735-L'],['server','业务服务器',50,560,'Dell','PowerEdge R350'],['switch','接入交换机',340,560,'H3C','S5130S'],['ap','办公区 AP',630,560,'TP-Link','EAP610']];model.nodes=spec.map(([t,name,x,y,brand,m])=>({...makeNode(t,x,y),name,brand,model:m,x:snapGrid(x),y:snapGrid(y)}));const link=(a,ap,b,bp,cable)=>model.edges.push({id:uid(),from:model.nodes[a].id,fromPort:model.nodes[a].ports[ap].id,to:model.nodes[b].id,toPort:model.nodes[b].ports[bp].id,cable});link(0,0,1,0,'cat6');link(1,1,2,0,'cat6a');link(2,1,3,0,'cat6');link(2,24,4,24,'sm');link(2,2,5,0,'cat6');selected.clear();selectedEdge=null;source=null;changed();fit();toast('示例已载入，所有设备与线路均可编辑')}
function svgExport(){if(!model.nodes.length){toast('请先添加设备');return null}const placed=endpointLayout(),bounds=diagramBounds(placed),x=bounds.x-40,y=bounds.y-70,w=bounds.w+80,h=bounds.h+140;const lines=model.edges.map(e=>{const r=route(e),c=model.cables.find(c=>c.id===e.cable);return `<path d="${r.d}" stroke="${c.color}" stroke-width="2.5" fill="none"/>`}).join('');const regions=model.nodes.filter(n=>n.type==='region').map(regionSvg).join('');const nodes=model.nodes.filter(n=>n.type!=='region').map(n=>n.type==='text'?textNodeSvg(n):`<g transform="translate(${n.x},${n.y})"><rect width="160" height="${nodeHeight(n)}" rx="11" fill="white" stroke="#dce2ee"/><svg x="13" y="22" width="29" height="29" viewBox="0 0 32 32" fill="none" stroke="#5263e8" stroke-width="1.6">${types[n.type][2]}</svg><text x="51" y="35" font-size="12" fill="#253449">${esc(n.name.length>12?n.name.slice(0,11)+'…':n.name)}</text><text x="51" y="52" font-size="9" fill="#9aa5b5">${types[n.type][1]}</text>${managementIpLines(n).map((line,i)=>`<text x="13" y="${67+i*14}" font-family="Consolas,monospace" font-size="10" fill="#5263aa">${esc(line)}</text>`).join('')}${n.expanded?`<text x="13" y="${91+managementIpHeight(n)}" font-size="10" fill="#7d8b9d"><tspan x="13">类型：${types[n.type][0]}</tspan><tspan x="13" dy="19">品牌：${esc(n.brand.slice(0,18)||'未设置')}</tspan><tspan x="13" dy="19">型号：${esc(n.model.slice(0,18)||'未设置')}</tspan></text>`:''}</g>`).join('');const labels=labelMarkup(placed);const legend=model.cables.map((c,i)=>`<rect x="${x+20+i*105}" y="${y+h-30}" width="14" height="3" fill="${c.color}"/><text x="${x+40+i*105}" y="${y+h-25}" fill="#8692a5" font-size="10">${esc(c.name)}</text>`).join('');const width=Math.max(w,600);return{w:width,h,svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${h}" viewBox="${x} ${y} ${width} ${h}" font-family="Segoe UI,Microsoft YaHei,sans-serif"><rect x="${x}" y="${y}" width="${width}" height="${h}" fill="#f8faff"/><text x="${x+20}" y="${y+35}" font-size="19" fill="#253449">${esc(model.name)}</text>${regions}${lines}${nodes}${labels}${legend}</svg>`}}
$('#exportSvg').onclick=()=>{const out=svgExport();if(out)download(new Blob([out.svg],{type:'image/svg+xml'}),filename()+'.svg')};$('#exportPng').onclick=async()=>{const out=svgExport();if(!out)return;const url=URL.createObjectURL(new Blob([out.svg],{type:'image/svg+xml'})),img=new Image();try{img.src=url;await img.decode();const c=document.createElement('canvas'),scale=Math.min(2,8192/out.w,8192/out.h,Math.sqrt(32000000/(out.w*out.h)));c.width=Math.ceil(out.w*scale);c.height=Math.ceil(out.h*scale);const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{if(b)download(b,filename()+'.png');else toast('图片导出失败')},'image/png')}catch{toast('图片导出失败，请尝试 SVG')}finally{URL.revokeObjectURL(url)}};
$('#selectTool').onclick=()=>setMode('select');$('#connectTool').onclick=()=>setMode('connect');$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);$('#delete').onclick=removeSelection;$('#fit').onclick=fit;$('#zoomIn').onclick=()=>zoom(1.2);$('#zoomOut').onclick=()=>zoom(1/1.2);$('#resetZoom').onclick=()=>zoom(1/view.z);$('#saveProject').onclick=save;$('#openProject').onclick=()=>$('#fileInput').click();$('#loadDemo').onclick=demo;$('#emptyDemo').onclick=demo;$('#newProject').onclick=()=>{checkpoint();model=blank();selected.clear();selectedEdge=null;source=null;view={x:50,y:50,z:1};changed();toast('已新建项目，可撤销返回上一个项目')};$('#projectName').onchange=e=>{checkpoint();model.name=e.target.value.trim().slice(0,120)||'未命名拓扑';changed(false)};
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||$('#connectionDialog').open)return;const ctrl=e.ctrlKey||e.metaKey;if(ctrl&&e.key.toLowerCase()==='s'){e.preventDefault();save()}else if(ctrl&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey)}else if(ctrl&&e.key.toLowerCase()==='y'){e.preventDefault();undo(true)}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelection()}else if(e.key===' '){e.preventDefault();space=true;canvas.style.cursor='grab'}else if(e.key==='Escape'){setMode('select');selected.clear();selectedEdge=null;render();renderInspector()}else if(e.key.toLowerCase()==='v')setMode('select');else if(e.key.toLowerCase()==='c'&&!ctrl)setMode('connect');else if(ctrl&&e.key.toLowerCase()==='a'){e.preventDefault();selected=new Set(model.nodes.map(n=>n.id));selectedEdge=null;changed()}});document.addEventListener('keyup',e=>{if(e.key===' '){space=false;canvas.style.cursor=''}});window.addEventListener('blur',()=>{if(gesture?.moved)persist();space=false;gesture=null;canvas.style.cursor=''});
try{const draft=localStorage.getItem('netsketch-draft-v1');if(draft)model=validate(JSON.parse(draft))}catch{toast('本地草稿不可用，请打开保存的项目文件')}render();renderInspector();if(model.nodes.length)requestAnimationFrame(fit);








$('#copy').onclick=copySelection;
