'use strict';
const M=RackModel,$=s=>document.querySelector(s),KEY='netsketch-racks-draft-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let project=M.empty(),roomId=null,selection=null,face='front',search='',history=[],future=[],dragId=null,dialogSave=null,toastTimer;
let colorBrush=null,quickConnection=null;
let restoreError='';
try{const saved=localStorage.getItem(KEY);if(saved)project=M.validate(JSON.parse(saved));}catch(e){restoreError='本地草稿未能读取，原草稿未覆盖。请打开备份项目文件。';}
roomId=project.rooms[0]?.id||null;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(project));$('#saveStatus').textContent='草稿已自动保存';}catch(e){$('#saveStatus').textContent='草稿保存失败，请保存到本地';toast('浏览器草稿存储失败，请点击“保存到本地”备份');}}
function checkpoint(){history.push(JSON.stringify(project));if(history.length>60)history.shift();future=[];}
function commit(action,{inspect=true}={}){checkpoint();action();persist();render(inspect);}
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(JSON.stringify(project));project=JSON.parse(from.pop());selection=null;normalizeRoom();persist();render();toast(redo?'已重做':'已撤销');}
function normalizeRoom(){if(!project.rooms.some(r=>r.id===roomId))roomId=project.rooms[0]?.id||null;}
function rackOfSelection(){if(selection?.kind==='device')return project.devices.find(d=>d.id===selection.id)?.rackId;if(selection?.kind==='pdu'||selection?.kind==='outlet')return project.pdus.find(p=>p.id===selection.id)?.rackId;if(selection?.kind==='rack')return selection.id;return project.racks.find(r=>r.roomId===roomId)?.id;}
function roomRacks(){return project.racks.filter(r=>r.roomId===roomId);}
function option(value,label,selected){return `<option value="${esc(value)}" ${selected===value?'selected':''}>${esc(label)}</option>`;}
function field(label,name,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function textField(label,name,value=''){return `<label>${label}<textarea name="${name}">${esc(value)}</textarea></label>`;}
function slotField(slot='full'){return selectField('宽度位置（从机柜正面看）','slot',[['full','全宽'],['left','左半宽'],['right','右半宽']],slot);}
function selectField(label,name,values,current){return `<label>${label}<select name="${name}">${values.map(v=>Array.isArray(v)?option(v[0],v[1],current):option(v,v,current)).join('')}</select></label>`;}
function openEditor(title,html,save){if(quickConnection)stopQuickConnection();if(colorBrush)stopColorBrush();$('#editorSubmit').textContent='保存';$('#editorTitle').textContent=title;$('#editorFields').innerHTML=html;$('#editorError').textContent='';dialogSave=save;$('#editor').showModal();}
$('#editorCancel').onclick=()=>$('#editor').close();
$('#editorForm').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));try{const error=dialogSave(values);if(error){$('#editorError').textContent=error;return;}$('#editor').close();}catch(error){$('#editorError').textContent=error.message;}};
function confirmAction(title,description,action){openEditor(title,`<p class="muted">${esc(description)}</p><p class="inline-note">操作后可点击撤销恢复。</p>`,()=>{action();});$('#editorSubmit').textContent='确认';}
function render(inspect=true){normalizeRoom();refreshColorBrush();$('#projectName').value=project.name;renderRooms();renderStats();renderBoard();if(inspect)renderInspector();$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;$('#addRack').disabled=!roomId;$('#editRoom').disabled=!roomId;$('#addDevice').disabled=!roomRacks().length;$('#frontView').classList.toggle('active',face==='front');$('#rearView').classList.toggle('active',face==='rear');$('#frontView').setAttribute('aria-pressed',face==='front');$('#rearView').setAttribute('aria-pressed',face==='rear');}
function renderRooms(){
  $('#roomList').innerHTML=project.rooms.map(room=>{const racks=project.racks.filter(r=>r.roomId===room.id);return `<button class="room-item ${room.id===roomId?'active':''}" data-room="${esc(room.id)}"><span>▦</span>${esc(room.name)}<small>${racks.length}</small></button>${room.id===roomId?racks.map(r=>`<button class="rack-link ${selectedRackId()===r.id?'active':''}" data-rack="${esc(r.id)}">${esc(r.name)}<small>${r.units}U</small></button>`).join(''):''}`;}).join('')||'<p class="muted">还没有机房，点击右上角 ＋ 开始。</p>';
  $('#roomCaption').textContent=roomId?`${project.rooms.find(r=>r.id===roomId).name} / ${face==='front'?'正面视图':'背面视图'}${search?' / 正在高亮搜索结果':''}`:'把机柜落位与电源接线，记录在一起';
}
function selectedRackId(){return selection?rackOfSelection():null;}
function renderStats(){const selected=project.racks.find(r=>r.id===selectedRackId()&&r.roomId===roomId),racks=selected?[selected]:roomRacks(),ids=new Set(racks.map(r=>r.id)),ds=project.devices.filter(d=>ids.has(d.rackId)),ps=project.pdus.filter(p=>ids.has(p.rackId));const used=racks.reduce((s,r)=>s+M.usedUnits(project,r.id),0),total=racks.reduce((s,r)=>s+r.units,0),outlets=ps.reduce((s,p)=>s+p.count-p.disabled.length,0),occupied=ps.reduce((sum,p)=>sum+Array.from({length:p.count},(_,i)=>M.outletUse(project,p.id,i+1)?1:0).reduce((a,b)=>a+b,0),0);$('#statsScope').innerHTML=`<span>${selected?'当前机柜 · '+esc(selected.name):'当前机房合计'}</span>${selected?'<button data-room-total>查看机房合计</button>':''}`;$('#stats').innerHTML='<div class="stats-values">'+[['机柜数量',racks.length,'个机柜'],['已上架设备',ds.length,'台 / 件'],['U 位占用',used,`/ ${total} U`],['已用插座',occupied,`/ ${outlets} 可用`]].map(([label,n,unit])=>`<div class="stat"><small>${label}</small><strong>${n}</strong><span>${unit}</span></div>`).join('')+'</div>';}
function isMatch(d){return !search||[d.name,d.type,d.brand,d.model,d.ip,d.serial,d.owner].join(' ').toLowerCase().includes(search);}
function railMarkup(rack,side){const selected=selection?.kind==='device'?project.devices.find(d=>d.id===selection.id):selection?.kind==='pdu'?project.pdus.find(p=>p.id===selection.id):null;return `<div class="pdu-rail">${project.pdus.filter(p=>p.rackId===rack.id&&p.side===side).map(p=>`<div class="pdu-strip"><button class="pdu-title ${side==='left'?'a':'b'}" data-pdu="${esc(p.id)}" title="${esc(p.name)} · ${esc(p.feed)}">${esc(p.name.replace(/^PDU\s*/i,''))}</button>${Array.from({length:p.count},(_,i)=>{const n=i+1,use=M.outletUse(project,p.id,n),linked=(selected?.power||[selected?.input].filter(Boolean)).some(x=>x.pduId===p.id&&x.outlet===n);return `<button class="outlet-dot ${use?'used':''} ${p.disabled.includes(n)?'disabled':''} ${linked?'linked':''}" data-outlet="${n}" data-pdu="${esc(p.id)}" style="${use?'--device-color:'+use.device.color:''}" aria-label="${esc(rack.name)} ${esc(p.name)} 插座 ${n}：${esc(use?use.device.name+' / '+use.power.label:p.disabled.includes(n)?'已停用':'空闲')}" title="${esc(p.name)} / ${n} · ${esc(use?use.device.name+' · '+use.power.label:p.disabled.includes(n)?'已停用':'空闲')}">${n}</button>`;}).join('')}</div>`).join('')}</div>`;}
function renderBoard(){
  const racks=roomRacks();
  if(!racks.length){$('#board').innerHTML=`<div class="empty-board"><div class="empty-icon">▤</div><div class="eyebrow">YOUR RACKS, CLEARLY MAPPED</div><h2>${roomId?'第一台机柜，从这里开始':'让每一台设备，都有迹可循'}</h2><p>按 U 位记录机柜落位，关联 PDU 插座。<br>设备位置、电源去向，一眼就能找到。</p><button class="primary" data-empty-add>${roomId?'＋ 新建机柜':'＋ 新建机房'}</button><button data-demo>查看示例机房</button></div>`;return;}
  $('#board').innerHTML=racks.map(r=>{const all=project.devices.filter(d=>d.rackId===r.id),ds=all.filter(d=>d.face===face||d.face==='both'),used=M.usedUnits(project,r.id);return `<article class="rack-card ${selectedRackId()===r.id?'rack-selected':''}" data-rack-card="${esc(r.id)}"><div class="rack-heading"><div><input class="rack-name-input" data-rack-name="${esc(r.id)}" aria-label="机柜名称：${esc(r.name)}" title="点击修改机柜名称，自动保存" maxlength="200" value="${esc(r.name)}"><small title="${esc(r.location||'未填写物理位置')} · ${r.units}U">${esc(r.location||'未填写物理位置')} · ${r.units}U</small></div></div><div class="rack-meter"><span style="width:${used/r.units*100}%"></span></div><div class="rack-body">${railMarkup(r,'left')}<div class="rack-face ${face==='rear'?'rear-face':''}" data-drop-rack="${esc(r.id)}" style="height:calc(${r.units} * var(--unit))">${Array.from({length:r.units},(_,i)=>{const u=r.units-i;return `<div class="u-row" data-u="${u}"><span>${u}</span><button data-add-at="${u}" data-rack="${esc(r.id)}" aria-label="在 ${esc(r.name)} U${u} 上架设备">＋ 上架</button><span>${u}</span></div>`;}).join('')}${ds.map(d=>`<button draggable="true" class="rack-device slot-${d.slot||'full'} ${selection?.kind==='device'&&selection.id===d.id?'selected':''} ${isMatch(d)?'':'dim'}" data-device="${esc(d.id)}" style="top:calc(${r.units-d.u-d.height+1} * var(--unit) + 1px);height:calc(${d.height} * var(--unit) - 2px);--device-color:${d.color}" title="${esc(d.name)} · U${d.u}${d.height>1?'–'+(d.u+d.height-1):''} · ${d.height}U${d.face==='both'?' · 前后贯通':''}"><strong>${esc(d.name)}</strong>${d.height>1?`<small>${esc(d.model||d.type)} · ${d.height}U</small>`:''}</button>`).join('')}</div>${railMarkup(r,'right')}</div><div class="rack-foot"><span>${all.length} 台设备 · 空闲 ${r.units-used}U</span><button data-add-pdu="${esc(r.id)}">＋ PDU</button></div></article>`;}).join('');
}
function select(kind,id,outlet){selection={kind,id,outlet};renderRooms();renderStats();refreshColorBrush();renderBoard();renderInspector();}
function jumpRack(id){selection={kind:'rack',id};render();const card=[...document.querySelectorAll('[data-rack-card]')].find(el=>el.dataset.rackCard===id);card?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});}
$('#roomList').onclick=e=>{const room=e.target.closest('[data-room]'),rack=e.target.closest('[data-rack]');if(room){roomId=room.dataset.room;selection=null;render();}else if(rack)jumpRack(rack.dataset.rack);};
$('#board').onclick=e=>{if(quickConnection){handleQuickConnection(e);return;}const t=e.target.closest('button');if(!t){if(e.target.closest('input'))return;const card=e.target.closest('[data-rack-card]');if(!colorBrush){selection=card?{kind:'rack',id:card.dataset.rackCard}:null;render();}return;}if(colorBrush){if(t.dataset.device)paintDevice(t.dataset.device);else toast('颜色刷已开启，请点击目标设备；Esc 退出');return;}if(t.hasAttribute('data-empty-add')){roomId?editRack():editRoom();return;}if(t.hasAttribute('data-demo')){loadDemo();return;}if(t.dataset.device){select('device',t.dataset.device);return;}if(t.dataset.outlet){select('outlet',t.dataset.pdu,Number(t.dataset.outlet));return;}if(t.dataset.pdu){select('pdu',t.dataset.pdu);return;}if(t.dataset.addPdu){editPdu(null,t.dataset.addPdu);return;}if(t.dataset.addAt){newDevice(t.dataset.rack,Number(t.dataset.addAt));return;}if(t.dataset.rack)select('rack',t.dataset.rack);};
function editRoom(existing){openEditor(existing?'编辑机房':'新建机房',field('机房名称','name',existing?.name||'', 'text','required maxlength="200"'),v=>{if(!v.name.trim())return '请填写机房名称';commit(()=>{if(existing)existing.name=v.name.trim();else{const room={id:M.id(),name:v.name.trim()};project.rooms.push(room);roomId=room.id;selection=null;}});});}
function editRack(existing){if(!roomId&&!existing)return editRoom();openEditor(existing?'编辑机柜':'新建机柜',field('机柜名称','name',existing?.name||'', 'text','required maxlength="200"')+selectField('所属机房','roomId',project.rooms.map(r=>[r.id,r.name]),existing?.roomId||roomId)+field('机柜高度（U）','units',existing?.units||42,'number','min="1" max="60" required')+field('长度（备注用）','length',existing?.length||'','text','placeholder="例如 1200 mm，可留空" maxlength="10000"')+field('物理位置 / 用途','location',existing?.location||'')+textField('备注','notes',existing?.notes||''),v=>{const units=Number(v.units);if(!v.name.trim())return '请填写机柜名称';if(!Number.isInteger(units)||units<1||units>60)return '机柜高度范围为 1–60U';if(existing&&project.devices.some(d=>d.rackId===existing.id&&d.u+d.height-1>units))return '缩小后的机柜高度不足，请先移动高位设备';commit(()=>{const data={name:v.name.trim(),roomId:v.roomId,units,length:v.length,location:v.location,notes:v.notes};if(existing)Object.assign(existing,data);else{existing={id:M.id(),...data};project.racks.push(existing);}roomId=existing.roomId;selection={kind:'rack',id:existing.id};});});}
function editPdu(existing,rackId){rackId=existing?.rackId||rackId;openEditor(existing?'编辑 PDU':'添加 PDU',field('PDU 名称','name',existing?.name||`PDU ${project.pdus.filter(p=>p.rackId===rackId).length?'B':'A'}`,'text','required maxlength="200"')+`<div class="row">${field('插座数量','count',existing?.count||12,'number','min="1" max="64" required')}${selectField('显示位置','side',[['left','机柜左侧'],['right','机柜右侧']],existing?.side||'left')}</div>`+selectField('插座类型','socketType',['C13','C19','国标五孔','混合 / 其他'],existing?.socketType||'C13')+field('供电来源','feed',existing?.feed||'','text','placeholder="例如 A 路 UPS / 市电"')+`<div class="row">${field('型号','model',existing?.model||'')}${field('额定电流（记录值）','rated',existing?.rated||'','text','placeholder="例如 16 A"')}</div>`+textField('备注','notes',existing?.notes||''),v=>{const count=Number(v.count);if(!v.name.trim())return '请填写 PDU 名称';if(!Number.isInteger(count)||count<1||count>64)return '插座数量范围为 1–64';if(existing&&Array.from({length:existing.count},(_,i)=>i+1).some(n=>n>count&&M.outletUse(project,existing.id,n)))return '待移除的插座仍连接设备，请先解除连接';commit(()=>{const data={...v,name:v.name.trim(),count,rackId,disabled:(existing?.disabled||[]).filter(n=>n<=count)};if(existing)Object.assign(existing,data);else{existing={id:M.id(),...data};project.pdus.push(existing);}selection={kind:'pdu',id:existing.id};});});}
function newDevice(rackId=rackOfSelection(),u){const rack=project.racks.find(r=>r.id===rackId);if(!rack){toast('请先新建机柜');return;}if(u===undefined){u=1;while(u<=rack.units&&M.placementError(project,{id:'',rackId,u,height:1,face:'both'}))u++;if(u>rack.units){toast('机柜没有完整空闲 U 位，请选择其他机柜或调整占用面');u=1;}}const d={id:M.id(),rackId,name:'',u,height:1,face:'both',slot:'full',type:'服务器',brand:'',model:'',serial:'',ip:'',owner:'',notes:'',color:M.COLORS[0],power:[]};openEditor('上架设备',field('设备名称','name','','text','required maxlength="200"')+selectField('设备类型','type',M.TYPES,d.type)+`<div class="row">${field('起始 U 位（顶部）','uTop',u,'number',`min="1" max="${rack.units}" required`)}${field('占用高度（U）','height',1,'number',`min="1" max="${rack.units}" required`)}</div>`+selectField('占用面','face',[['both','前后贯通（服务器等）'],['front','仅前侧（配线架、盲板等）'],['rear','仅后侧']],d.face)+slotField(d.slot)+`<p class="inline-note">例如顶部 U=20、高度=2，占用 U19–U20。完整设备选择前后贯通，避免前后重复上架。</p>`,v=>{const {uTop,...values}=v;const next={...d,...values,name:v.name.trim(),u:Number(uTop)-Number(v.height)+1,height:Number(v.height)};if(!next.name)return '请填写设备名称';const error=M.placementError(project,next);if(error)return error;commit(()=>{project.devices.push(next);selection={kind:'device',id:next.id};face=next.face==='rear'?'rear':'front';});});}
function renderInspector(){
  const host=$('#inspector');
  if(!selection){$('#inspectorTitle').textContent='落位详情';host.innerHTML='<div class="empty-properties"><div class="empty-icon">▤</div><strong>选择一台设备或一个插座</strong><p>查看落位与电源去向。<br>选中机柜，可在右侧编辑机柜及 PDU。</p><p>设备同色插座：已连接<br>白色插座：空闲<br>斜纹插座：停用</p></div>';return;}
  if(selection.kind==='device')return deviceInspector(project.devices.find(d=>d.id===selection.id));
  if(selection.kind==='rack')return rackInspector(project.racks.find(r=>r.id===selection.id));
  const p=project.pdus.find(p=>p.id===selection.id);if(!p){selection=null;return renderInspector();}
  selection.kind==='outlet'?outletInspector(p,selection.outlet):pduInspector(p);
}
function deviceInspector(d){if(!d){selection=null;return renderInspector();}const r=project.racks.find(r=>r.id===d.rackId);$('#inspectorTitle').textContent='设备属性';$('#inspector').innerHTML=`<span class="badge">${esc(r.name)} · U${d.u}${d.height>1?'–'+(d.u+d.height-1):''}</span><form id="deviceForm">${field('设备名称','name',d.name,'text','required maxlength="200"')}${selectField('设备类型','type',M.TYPES.includes(d.type)?M.TYPES:[...M.TYPES,d.type],d.type)}<div class="row">${field('起始 U（顶部）','uTop',d.u+d.height-1,'number',`min="1" max="${r.units}" required`)}${field('高度（U）','height',d.height,'number',`min="1" max="${r.units}" required`)}</div>${selectField('占用面','face',[['both','前后贯通'],['front','仅前侧'],['rear','仅后侧']],d.face)}${slotField(d.slot)}<div class="row">${field('品牌','brand',d.brand)}${field('型号','model',d.model)}</div>${textField('管理 IP','ip',d.ip)}<details><summary>资产信息与备注</summary>${field('序列号','serial',d.serial)}${field('设备归属','owner',d.owner)}${textField('备注','notes',d.notes)}</details>${field('设备颜色','color',d.color,'color')}<p id="deviceError" class="error" role="alert"></p></form><div class="section-heading"><h3>电源接线 <small>${d.power.length} 路</small></h3><button id="addPower">＋ 连接</button></div><p class="inline-note">同一插座只能连接一个电源接口。A / B 供电来源按实际填写。</p>${d.power.map((p,i)=>{const pdu=project.pdus.find(x=>x.id===p.pduId);return `<div class="power-card"><button data-disconnect="${i}" title="解除此电源连接" aria-label="解除 ${esc(p.label)} 连接">×</button><strong>${esc(p.label)} → ${esc(pdu.name)} / ${p.outlet}</strong><small>${esc(pdu.feed||'供电来源未填写')} · ${esc(pdu.socketType)}</small>${p.notes?`<small>${esc(p.notes)}</small>`:''}</div>`;}).join('')||'<p class="muted">尚未记录电源连接。</p>'}<div class="form-actions"><button id="moveDevice">移动到机柜</button><button id="removeDevice" class="danger">下架设备</button></div>`;
  const form=$('#deviceForm');let editCheckpoint=false;
  form.onsubmit=e=>e.preventDefault();
  form.addEventListener('focusin',()=>{editCheckpoint=false;});
  function saveField(e){
    const input=e.target,key=input.name;if(!key||e.isComposing)return;
    const value=['uTop','height'].includes(key)?Number(input.value):key==='name'?input.value.trim():input.value;
    const patch=key==='uTop'?{u:value-d.height+1}:key==='height'?{u:d.u+d.height-value,height:value}:{[key]:value};
    const next={...d,...patch};
    const error=!next.name?'设备名称不能为空':!input.checkValidity()?'请填写有效的属性值':M.placementError(project,next);
    input.setAttribute('aria-invalid',String(!!error));$('#deviceError').textContent=error?error+'（未保存此项）':'';
    if(error||Object.keys(patch).every(k=>d[k]===patch[k]))return;
    if(!editCheckpoint){checkpoint();editCheckpoint=true;}
    Object.assign(d,patch);persist();render(false);
    const badge=$('#inspector > .badge');if(badge)badge.textContent=r.name+' · U'+d.u+(d.height>1?'–'+(d.u+d.height-1):'');
  }
  form.addEventListener('input',saveField);form.addEventListener('change',saveField);form.addEventListener('compositionend',saveField);
  form.addEventListener('focusout',e=>{const input=e.target;if(input.getAttribute('aria-invalid')==='true'){input.value=input.name==='uTop'?d.u+d.height-1:d[input.name]??'';input.removeAttribute('aria-invalid');$('#deviceError').textContent+='，已恢复原值';}});
  $('#addPower').onclick=()=>connectPower(d);
  $('#inspector').querySelectorAll('[data-disconnect]').forEach(b=>b.onclick=()=>commit(()=>d.power.splice(Number(b.dataset.disconnect),1)));
  $('#removeDevice').onclick=()=>removeDevice(d);
  $('#moveDevice').onclick=()=>moveDeviceDialog(d);
}
function removeDevice(d){commit(()=>{project.devices=project.devices.filter(x=>x.id!==d.id);selection={kind:'rack',id:d.rackId};});toast('设备已下架，电源连接已解除 · 可撤销');}
function moveDeviceDialog(d,targetRackId=d.rackId,targetU=d.u){openEditor('移动设备',selectField('目标机柜','rackId',project.racks.map(r=>[r.id,`${project.rooms.find(x=>x.id===r.roomId).name} / ${r.name}`]),targetRackId)+field('目标起始 U（顶部）','uTop',targetU+d.height-1,'number','min="1" max="60" required')+'<p class="muted">跨机柜移动会解除原 PDU 接线，请在目标机柜重新连接。</p>',v=>{const next={...d,rackId:v.rackId,u:Number(v.uTop)-d.height+1};const error=M.placementError(project,next);if(error)return error;commit(()=>{if(next.rackId!==d.rackId)d.power=[];d.rackId=next.rackId;d.u=next.u;roomId=project.racks.find(r=>r.id===d.rackId).roomId;selection={kind:'device',id:d.id};});});}
function rackInspector(r){if(!r){selection=null;return renderInspector();}$('#inspectorTitle').textContent='机柜与配电';const ps=project.pdus.filter(p=>p.rackId===r.id);$('#inspector').innerHTML=`<span class="badge">${r.units}U · ${M.usedUnits(project,r.id)}U 已占用</span><h2>${esc(r.name)}</h2><p class="muted">${esc(r.location||'尚未填写物理位置')}</p>${r.length?`<p class="muted">长度：${esc(r.length)}</p>`:''}${r.notes?`<p class="muted">${esc(r.notes)}</p>`:''}<button class="wide" id="editRack">编辑机柜</button><div class="section-heading"><h3>PDU 配置</h3><button id="newPdu">＋ 添加</button></div>${ps.map(p=>`<button class="pdu-option" data-open-pdu="${esc(p.id)}"><strong>${esc(p.name)}</strong><small>${esc(p.feed||'未填写供电来源')} · ${p.count} 位 ${esc(p.socketType)}</small></button>`).join('')||'<p class="muted">添加 PDU 后，即可记录插座与设备电源的连接。</p>'}<p class="inline-note">插座显示在机柜两侧，不占用 U 位。横装 PDU 可另外添加一台类型为“其他”的设备来记录实际占用位置。</p><button class="danger wide" id="removeRack">删除机柜</button>`;$('#editRack').onclick=()=>editRack(r);$('#newPdu').onclick=()=>editPdu(null,r.id);$('#inspector').querySelectorAll('[data-open-pdu]').forEach(b=>b.onclick=()=>select('pdu',b.dataset.openPdu));$('#removeRack').onclick=()=>{if(project.devices.some(d=>d.rackId===r.id)){toast('请先下架或移走机柜内设备');return;}if(project.pdus.some(p=>p.input&&(p.rackId===r.id||ps.some(x=>x.id===p.input.pduId)))){toast('请先解除机柜的 PDU 级联连接');return;}confirmAction('删除机柜',`删除「${r.name}」及其 PDU 配置。`,()=>commit(()=>{project.racks=project.racks.filter(x=>x.id!==r.id);project.pdus=project.pdus.filter(x=>x.rackId!==r.id);selection=null;}));};}
function pduInspector(p){const occupied=Array.from({length:p.count},(_,i)=>M.outletUse(project,p.id,i+1)?1:0).reduce((a,b)=>a+b,0);$('#inspectorTitle').textContent='PDU 插座';$('#inspector').innerHTML=`<span class="badge">${esc(project.racks.find(r=>r.id===p.rackId).name)}</span><h2>${esc(p.name)}</h2><p class="muted">${esc(p.feed||'未填写供电来源')}<br>${p.count} 位 ${esc(p.socketType)}${p.rated?' · '+esc(p.rated):''}<br>已用 ${occupied} · 空闲 ${p.count-p.disabled.length-occupied} · 停用 ${p.disabled.length}</p>${pduInputMarkup(p)}<button id="editPdu" class="wide">编辑 PDU 配置</button><div class="socket-list">${Array.from({length:p.count},(_,i)=>{const n=i+1,use=M.outletUse(project,p.id,n);return `<button class="socket-row ${use?'used':''}" style="${use?'--device-color:'+use.device.color:''}" data-socket="${n}"><span>${n}</span><div>${esc(use?use.device.name:p.disabled.includes(n)?'已停用':'空闲插座')}${use?`<small>${esc(use.power.label)}</small>`:''}</div><span class="socket-state">${use?'已连接':'›'}</span></button>`;}).join('')}</div><button id="removePdu" class="danger wide">删除 PDU</button>`;bindPduInput(p);$('#editPdu').onclick=()=>editPdu(p);$('#inspector').querySelectorAll('[data-socket]').forEach(b=>b.onclick=()=>select('outlet',p.id,Number(b.dataset.socket)));$('#removePdu').onclick=()=>{if(occupied||p.input){toast('请先解除 PDU 的上级供电和下游连接');return;}confirmAction('删除 PDU',`删除「${p.name}」及其插座配置。`,()=>commit(()=>{project.pdus=project.pdus.filter(x=>x.id!==p.id);selection={kind:'rack',id:p.rackId};}));};}
function outletInspector(p,n){const use=M.outletUse(project,p.id,n),disabled=p.disabled.includes(n);$('#inspectorTitle').textContent='插座详情';$('#inspector').innerHTML=`<button id="backPdu">‹ ${esc(p.name)}</button><div class="outlet-detail"><span class="badge">插座 ${n} · ${esc(p.socketType)}</span><h2>${esc(p.name)} / ${n}</h2><small>${esc(p.feed||'未填写供电来源')}</small><p>${use?`${esc(use.device.name)}<br><strong>${esc(use.power.label)}</strong>`:disabled?'此插座已停用':'此插座空闲'}</p>${use?.power.notes?`<p class="muted">${esc(use.power.notes)}</p>`:''}</div>${use?'<button class="wide primary" id="viewPoweredDevice">查看关联设备</button><button class="wide" id="disconnectOutlet">解除连接</button>':`${!disabled?'<button class="wide primary" id="connectOutlet">连接设备电源</button>':''}<button class="wide" id="toggleOutlet">${disabled?'恢复使用':'停用此插座'}</button>`}`;$('#backPdu').onclick=()=>select('pdu',p.id);if(use){$('#viewPoweredDevice').onclick=()=>{if(use.kind==='pdu'){showPdu(use.device.id);return;}face=use.device.face==='rear'?'rear':'front';select('device',use.device.id);render();};$('#disconnectOutlet').onclick=()=>commit(()=>{if(use.kind==='pdu')delete project.pdus.find(p=>p.id===use.device.id).input;else use.device.power=use.device.power.filter(x=>x!==use.power);});}else{$('#toggleOutlet').onclick=()=>commit(()=>{p.disabled=disabled?p.disabled.filter(x=>x!==n):[...p.disabled,n];});if(!disabled)$('#connectOutlet').onclick=()=>connectPower(null,p,n);}}
function connectPower(device,presetPdu,presetOutlet){
  const rackId=device?.rackId||presetPdu.rackId,pdus=project.pdus.filter(p=>p.rackId===rackId),devices=project.devices.filter(d=>d.rackId===rackId);
  if(!pdus.length){toast('请先为机柜添加 PDU');return;}if(!devices.length){toast('请先上架设备');return;}
  const available=[];for(const p of pdus)for(let n=1;n<=p.count;n++)if(!p.disabled.includes(n)&&!M.outletUse(project,p.id,n))available.push({p,n});if(!available.length){toast('本机柜没有空闲可用插座');return;}
  const target=available.find(a=>a.p.id===presetPdu?.id&&a.n===presetOutlet)||available[0];
  let nextPsu=1;const sourceDevice=device||devices[0];while(sourceDevice.power.some(p=>p.label.trim().toLowerCase()===`psu${nextPsu}`))nextPsu++;
  openEditor('连接设备电源',selectField('设备','deviceId',(device?[device]:devices).map(d=>[d.id,d.name]),device?.id||devices[0].id)+field('电源接口名称','label',`PSU${nextPsu}`,'text','required maxlength="80"')+selectField('PDU / 插座号','target',available.map(a=>[`${a.p.id}|${a.n}`,`${a.p.name} / ${a.n} · ${a.p.feed||a.p.socketType}`]),`${target.p.id}|${target.n}`)+textField('接线备注','notes','')+'<p class="inline-note">仅列出本机柜的空闲、未停用插座。插座状态根据记录计算，不代表实时通断电。</p>',v=>{const d=project.devices.find(d=>d.id===v.deviceId),found=available.find(a=>`${a.p.id}|${a.n}`===v.target);if(!d||!found)return '设备或插座已变更，请重新选择';const power={label:v.label.trim(),pduId:found.p.id,outlet:found.n,notes:v.notes};const error=M.powerError(project,{...d,power:[...d.power,power]});if(error)return error;commit(()=>{d.power.push(power);selection={kind:'device',id:d.id};});});
}
$('#board').addEventListener('dragstart',e=>{if(colorBrush||quickConnection){e.preventDefault();return;}const node=e.target.closest('[data-device]');if(!node)return;dragId=node.dataset.device;e.dataTransfer.setData('text/plain',dragId);e.dataTransfer.effectAllowed='move';node.classList.add('dragging');});
function dropPoint(e){const target=e.target.closest('[data-drop-rack]');if(!target)return null;const r=project.racks.find(r=>r.id===target.dataset.dropRack),rect=target.getBoundingClientRect();return {r,u:Math.max(1,Math.min(r.units,r.units-Math.floor((e.clientY-rect.top)/(rect.height/r.units))))};}
$('#board').addEventListener('dragover',e=>{if(!dragId)return;const point=dropPoint(e);if(!point)return;e.preventDefault();e.dataTransfer.dropEffect='move';document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));const rack=[...document.querySelectorAll('[data-drop-rack]')].find(el=>el.dataset.dropRack===point.r.id);const d=project.devices.find(d=>d.id===dragId);for(let u=point.u;u>=Math.max(1,point.u-(d?.height||1)+1);u--)rack?.querySelector(`[data-u="${u}"]`)?.classList.add('drop-target');});
$('#board').addEventListener('drop',e=>{if(!dragId)return;e.preventDefault();const point=dropPoint(e),d=project.devices.find(d=>d.id===dragId);dragId=null;$('.drop-target')?.classList.remove('drop-target');$('.dragging')?.classList.remove('dragging');if(!point||!d)return;const u=point.u-d.height+1,next={...d,rackId:point.r.id,u},error=M.placementError(project,next);if(error){toast(error);return;}if(next.rackId===d.rackId&&u===d.u){select('device',d.id);return;}if(next.rackId!==d.rackId&&d.power.length){moveDeviceDialog(d,next.rackId,u);return;}commit(()=>{d.rackId=next.rackId;d.u=u;selection={kind:'device',id:d.id};});toast(`已移动至 ${point.r.name} · 顶部 U${point.u}${d.height>1?' · 占用 U'+u+'–'+point.u:''}`);});
$('#board').addEventListener('dragend',()=>{dragId=null;$('.drop-target')?.classList.remove('drop-target');$('.dragging')?.classList.remove('dragging');});
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function filename(){return (project.name||'机柜记录').replace(/[\\/:*?"<>|]/g,'_');}
function saveProject(){download(JSON.stringify(project,null,2),'application/json',filename()+'.racks.json');toast('已生成本地项目文件');}
function loadDemo(){const load=()=>commit(()=>{project=M.demo();roomId=project.rooms[0].id;selection=null;});if(project.rooms.length)confirmAction('载入示例机房','这会替换当前机柜记录，建议先保存本地文件。示例按三楼机房的布局制作，不代表实际资产或接线。',load);else load();}
$('#addRoom').onclick=()=>editRoom();$('#editRoom').onclick=()=>{const room=project.rooms.find(r=>r.id===roomId);openEditor('编辑机房',field('机房名称','name',room.name,'text','required maxlength="200"')+(!project.racks.some(r=>r.roomId===roomId)?'<p class="inline-note">机房为空，可以删除。</p><button type="button" id="removeRoom" class="danger">删除空机房</button>':''),v=>{if(!v.name.trim())return '请填写机房名称';commit(()=>room.name=v.name.trim());});const remove=$('#removeRoom');if(remove)remove.onclick=()=>{$('#editor').close();commit(()=>{project.rooms=project.rooms.filter(r=>r.id!==roomId);roomId=null;selection=null;});};};
$('#addRack').onclick=()=>editRack();$('#addDevice').onclick=()=>newDevice();$('#loadDemo').onclick=loadDemo;
$('#projectName').onchange=e=>{const name=e.target.value.trim()||'机房落位记录';if(name===project.name)return;commit(()=>project.name=name,{inspect:false});};
$('#frontView').onclick=()=>{face='front';render();};$('#rearView').onclick=()=>{face='rear';render();};
$('#search').oninput=e=>{search=e.target.value.trim().toLowerCase();renderRooms();renderBoard();const matches=project.devices.filter(d=>roomRacks().some(r=>r.id===d.rackId)&&isMatch(d));$('#hint').textContent=search?`找到 ${matches.length} 台设备（背面专用设备需切换背面查看）`:'点击空闲 U 位上架设备 · 拖动设备调整落位';refreshColorBrush();};
$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);$('#saveProject').onclick=saveProject;$('#openProject').onclick=()=>$('#fileInput').click();
$('#newProject').onclick=()=>confirmAction('新建机柜项目','当前机柜记录将被替换，建议先保存本地项目文件。',()=>commit(()=>{project=M.empty();roomId=null;selection=null;}));
$('#fileInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>20*1024*1024){toast('项目文件超过 20 MB，无法打开');return;}let next;try{next=M.validate(JSON.parse(await file.text()));}catch(error){toast(error.message);return;}const load=()=>commit(()=>{project=next;roomId=project.rooms[0]?.id||null;selection=null;});if(project.rooms.length)confirmAction('打开机柜项目',`载入「${next.name}」并替换当前记录，建议先保存当前项目。`,load);else load();};
$('#exportCsv').onclick=()=>{download(M.csv(project),'text/csv;charset=utf-8',filename()+'.csv');toast('已导出设备与电源连接表，可用 Excel 打开');};$('#print').onclick=()=>window.print();
document.addEventListener('keydown',e=>{if($('#editor').open)return;if(e.key==='Escape'&&quickConnection){e.preventDefault();stopQuickConnection();return;}if(e.key==='Escape'&&colorBrush){e.preventDefault();stopColorBrush();return;}if(e.key==='Escape'&&document.body.classList.contains('rack-fullscreen')){e.preventDefault();exitRackFullscreen();return;}const editing=e.target.matches('input,textarea,select');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject();return;}if(editing||e.target.isContentEditable)return;if(e.key==='Delete'&&selection?.kind==='device'){e.preventDefault();const d=project.devices.find(d=>d.id===selection.id);if(d)removeDevice(d);return;}if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();undo(e.shiftKey||e.key.toLowerCase()==='y');}});
function refreshColorBrush(){refreshQuickConnection();
  const button=$('#colorBrush'),source=selection?.kind==='device'?project.devices.find(d=>d.id===selection.id):null;
  button.disabled=!colorBrush&&!source;button.classList.toggle('active',!!colorBrush);button.setAttribute('aria-pressed',String(!!colorBrush));
  button.querySelector('.brush-label').textContent=colorBrush?'结束刷色':'颜色刷';
  button.querySelector('.brush-swatch').style.background=colorBrush?.color||source?.color||'#c0c8d5';
  button.title=colorBrush?'连续点击设备应用颜色；再次点击或 Esc 退出':source?'复制所选设备颜色':'先选中设备，复制其颜色';
  $('#board').classList.toggle('color-brush-mode',!!colorBrush);
  if(colorBrush)$('#hint').textContent='颜色刷 · 来源：'+colorBrush.name+' · 连续点击目标设备，Esc 退出';
}
function stopColorBrush(){colorBrush=null;refreshColorBrush();$('#hint').textContent='点击空闲 U 位上架设备 · 拖动设备调整落位';}
function paintDevice(id){const d=project.devices.find(d=>d.id===id);if(!colorBrush||!d)return;if(d.color.toLowerCase()===colorBrush.color.toLowerCase()){select('device',id);return;}const color=colorBrush.color;commit(()=>{d.color=color;selection={kind:'device',id};});toast('已应用颜色，关联 PDU 插座同步更新 · 可继续刷色');}
$('#colorBrush').onclick=()=>{if(quickConnection)stopQuickConnection();if(colorBrush){stopColorBrush();return;}const d=selection?.kind==='device'?project.devices.find(d=>d.id===selection.id):null;if(!d)return;colorBrush={color:d.color,name:d.name};refreshColorBrush();toast('颜色已复制，点击其他设备连续刷色；Esc 退出');};
render();if(restoreError)toast(restoreError);

function rackImageName(){const room=project.rooms.find(r=>r.id===roomId);return (filename()+'-'+(room?.name||'机房')+'-'+(face==='rear'?'背面':'正面')).replace(/[\\/:*?"<>|]/g,'_');}
function exportRackSvg(){try{const result=RackExport.svg(project,roomId,face);download(result.content,'image/svg+xml;charset=utf-8',rackImageName()+'.svg');toast('已导出当前机房完整 SVG');}catch(error){toast(error.message);}}
async function exportRackPng(){let url;try{const result=RackExport.svg(project,roomId,face);const scale=Math.min(2,16384/result.width,16384/result.height,Math.sqrt(64000000/(result.width*result.height)));if(scale<0.5)throw Error('当前机房过大，请使用 SVG 导出');url=URL.createObjectURL(new Blob([result.content],{type:'image/svg+xml;charset=utf-8'}));const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('图片生成失败，请使用 SVG 导出'));img.src=url;});const canvas=document.createElement('canvas');canvas.width=Math.ceil(result.width*scale);canvas.height=Math.ceil(result.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw Error('浏览器无法生成 PNG，请使用 SVG 导出');ctx.scale(scale,scale);ctx.drawImage(img,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG 生成失败，请使用 SVG 导出');download(blob,'image/png',rackImageName()+'.png');toast('已导出当前机房完整 PNG');}catch(error){toast(error.message);}finally{if(url)URL.revokeObjectURL(url);}}
$('#exportSvg').onclick=exportRackSvg;$('#exportPng').onclick=exportRackPng;

$('#board').addEventListener('focusin',e=>{if(e.target.matches('.rack-name-input')){e.target.dataset.checkpoint='0';selection={kind:'rack',id:e.target.dataset.rackName};renderRooms();renderStats();renderInspector();refreshColorBrush();document.querySelectorAll('[data-rack-card]').forEach(card=>card.classList.toggle('rack-selected',card.dataset.rackCard===selectedRackId()));}});
function saveRackName(e){const input=e.target;if(!input.matches('.rack-name-input')||e.isComposing)return;const r=project.racks.find(r=>r.id===input.dataset.rackName);if(!r)return;const name=input.value.trim();input.setAttribute('aria-invalid',String(!name));if(!name||name===r.name)return;if(input.dataset.checkpoint!=='1'){checkpoint();input.dataset.checkpoint='1';}r.name=name;persist();renderRooms();renderStats();renderInspector();$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;}
$('#board').addEventListener('input',saveRackName);$('#board').addEventListener('compositionend',saveRackName);
$('#board').addEventListener('focusout',e=>{const input=e.target;if(!input.matches('.rack-name-input'))return;const r=project.racks.find(r=>r.id===input.dataset.rackName);if(!r)return;if(!input.value.trim())toast('机柜名称不能为空，已恢复原名称');input.value=r.name;input.removeAttribute('aria-invalid');input.setAttribute('aria-label','机柜名称：'+r.name);});
$('#board').addEventListener('keydown',e=>{if(e.target.matches('.rack-name-input')&&e.key==='Enter'&&!e.isComposing){e.preventDefault();e.target.blur();}});

$('#statsScope').onclick=e=>{if(e.target.closest('[data-room-total]')){selection=null;render();}};
function setRackPanelCollapsed(side,collapsed){const left=side==='left',panel=left?$('#roomsPanel'):$('#propertiesPanel'),button=left?$('#toggleRooms'):$('#toggleProperties');panel.hidden=collapsed;$('.app-layout').classList.toggle(left?'rooms-collapsed':'properties-collapsed',collapsed);button.setAttribute('aria-expanded',String(!collapsed));button.textContent=left?(collapsed?'›':'‹'):(collapsed?'‹':'›');const label=(collapsed?'展开':'收起')+(left?'机房列表':'属性栏');button.title=label;button.setAttribute('aria-label',label);}
function toggleRackPanel(side){setRackPanelCollapsed(side,!(side==='left'?$('#roomsPanel'):$('#propertiesPanel')).hidden);}
$('#toggleRooms').onclick=()=>toggleRackPanel('left');$('#toggleProperties').onclick=()=>toggleRackPanel('right');

let rackFullscreenPanels=null;
function setRackFullscreen(active){if(active===document.body.classList.contains('rack-fullscreen'))return;if(active){rackFullscreenPanels={left:$('#roomsPanel').hidden,right:$('#propertiesPanel').hidden};setRackPanelCollapsed('left',true);setRackPanelCollapsed('right',true);}else if(rackFullscreenPanels){setRackPanelCollapsed('left',rackFullscreenPanels.left);setRackPanelCollapsed('right',rackFullscreenPanels.right);rackFullscreenPanels=null;}document.body.classList.toggle('rack-fullscreen',active);const button=$('#rackFullscreen');button.textContent=active?'⛶ 退出全屏':'⛶ 全屏';button.title=active?'退出全屏（Esc）':'全屏机柜工作区';button.setAttribute('aria-pressed',String(active));}
async function exitRackFullscreen(){if(document.fullscreenElement){try{await document.exitFullscreen();}catch{}}setRackFullscreen(false);}
$('#rackFullscreen').onclick=async()=>{if(document.body.classList.contains('rack-fullscreen')){await exitRackFullscreen();return;}setRackFullscreen(true);try{await document.documentElement.requestFullscreen();}catch{/* Unsupported browsers keep the page fullscreen layout. */}};
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)setRackFullscreen(false);});

function refreshQuickConnection(){const active=!!quickConnection;$('#rackSelectTool').classList.toggle('mode-active',!active&&!colorBrush);$('#rackSelectTool').setAttribute('aria-pressed',String(!active&&!colorBrush));$('#rackConnectTool').classList.toggle('mode-active',active);$('#rackConnectTool').setAttribute('aria-pressed',String(active));$('#board').classList.toggle('quick-connect-mode',active);if(active){const d=project.devices.find(d=>d.id===quickConnection.deviceId),p=project.pdus.find(p=>p.id===quickConnection.pduId);$('#hint').textContent=p?'为 '+p.name+' 连接上级供电 · 点击上级 PDU 空闲插座（可跨机柜）':d?'连接 '+d.name+' · 点击同机柜空闲插座':'连接模式 · 先点击设备或下级 PDU 名称，再点击上级插座 · Esc 取消';}}
function stopQuickConnection(){quickConnection=null;refreshQuickConnection();$('#hint').textContent='点击空闲 U 位上架设备 · 拖动设备调整落位';}
function handleQuickConnection(e){const button=e.target.closest('button');if(!button)return;if(button.dataset.device){quickConnection={deviceId:button.dataset.device};select('device',button.dataset.device);return;}if(!button.dataset.pdu){toast('请选择设备、下级 PDU 名称或上级插座');return;}const d=project.devices.find(d=>d.id===quickConnection.deviceId),child=project.pdus.find(p=>p.id===quickConnection.pduId);if(!d&&!child){if(button.dataset.outlet){toast('请先点击设备或下级 PDU 名称');return;}quickConnection={pduId:button.dataset.pdu};select('pdu',button.dataset.pdu);return;}try{const outlet=button.dataset.outlet?Number(button.dataset.outlet):undefined,power=child?M.defaultPduInput(project,child,button.dataset.pdu,outlet):M.defaultPower(project,d,button.dataset.pdu,outlet),parent=project.pdus.find(p=>p.id===power.pduId);stopQuickConnection();commit(()=>{if(child)child.input=power;else d.power.push(power);selection={kind:child?'pdu':'device',id:(child||d).id};});toast(power.label+' → '+parent.name+' / '+power.outlet+'，已切回选择');}catch(error){toast(error.message);}}
function showPdu(id){const p=project.pdus.find(p=>p.id===id);roomId=project.racks.find(r=>r.id===p.rackId).roomId;selection={kind:'pdu',id};render();}
function pduInputMarkup(p){const up=project.pdus.find(x=>x.id===p.input?.pduId),r=project.racks.find(r=>r.id===up?.rackId);return '<div class="power-card"><strong>上级供电 · INPUT</strong><small>'+esc(up?r.name+' → '+up.name+' → 插座 '+p.input.outlet:'未连接上级 PDU')+'</small></div><div class="form-actions"><button id="changePduInput">'+(up?'更换上级':'连接上级')+'</button>'+(up?'<button id="viewPduInput">查看上级</button><button id="removePduInput">解除连接</button>':'')+'</div>';}
function bindPduInput(p){$('#changePduInput').onclick=()=>editPduInput(p);if(p.input){$('#viewPduInput').onclick=()=>showPdu(p.input.pduId);$('#removePduInput').onclick=()=>commit(()=>delete p.input);}}
function editPduInput(p){const choices=[];for(const up of project.pdus){for(let n=1;n<=up.count;n++){const input={label:'INPUT',pduId:up.id,outlet:n};if(!M.pduInputError(project,p,input)){const r=project.racks.find(r=>r.id===up.rackId),room=project.rooms.find(x=>x.id===r.roomId);choices.push({input,label:room.name+' / '+r.name+' / '+up.name+' / '+n});}}}if(!choices.length){toast('没有可用的上级 PDU 插座');return;}openEditor('连接上级 PDU',selectField('上级插座','target',choices.map((c,i)=>[String(i),c.label]),String(Math.max(0,choices.findIndex(c=>c.input.pduId===p.input?.pduId&&c.input.outlet===p.input?.outlet))))+'<p class="inline-note">接口名称为 INPUT，每台 PDU 仅记录一个供电输入。</p>',v=>{const input=choices[Number(v.target)]?.input,error=M.pduInputError(project,p,input);if(error)return error;stopQuickConnection();commit(()=>p.input={...input,notes:''});});}
$('#rackConnectTool').onclick=()=>{if(quickConnection){stopQuickConnection();return;}if(colorBrush)stopColorBrush();quickConnection={deviceId:null};refreshQuickConnection();};
$('#rackSelectTool').onclick=()=>{if(colorBrush)stopColorBrush();stopQuickConnection();};

function installBoardPan(scroller){
  let pan=null,suppressClick=false;
  scroller.addEventListener('pointerdown',e=>{
    suppressClick=false;
    if(e.button!==0||e.target.closest('input,textarea,select,a,[contenteditable="true"]'))return;
    const button=e.target.closest('button');
    if(button&&!button.hasAttribute('data-add-at'))return;
    const rect=scroller.getBoundingClientRect();
    if(e.clientX>=rect.left+scroller.clientWidth||e.clientY>=rect.top+scroller.clientHeight)return;
    pan={id:e.pointerId,x:e.clientX,y:e.clientY,left:scroller.scrollLeft,top:scroller.scrollTop,dragged:false};
  });
  scroller.addEventListener('pointermove',e=>{
    if(!pan||pan.id!==e.pointerId)return;
    const dx=e.clientX-pan.x,dy=e.clientY-pan.y;
    if(!pan.dragged&&Math.hypot(dx,dy)<4)return;
    if(!pan.dragged){pan.dragged=true;scroller.setPointerCapture(e.pointerId);scroller.classList.add('board-panning');}
    e.preventDefault();scroller.scrollLeft=pan.left-dx;scroller.scrollTop=pan.top-dy;
  });
  const finish=e=>{if(!pan||e.pointerId!==pan.id)return;suppressClick=pan.dragged;pan=null;scroller.classList.remove('board-panning');if(scroller.hasPointerCapture(e.pointerId))scroller.releasePointerCapture(e.pointerId);};
  scroller.addEventListener('pointerup',finish);
  scroller.addEventListener('pointercancel',finish);
  scroller.addEventListener('lostpointercapture',finish);
  scroller.addEventListener('click',e=>{if(suppressClick){suppressClick=false;e.preventDefault();e.stopImmediatePropagation();}},true);
}
installBoardPan($('#boardScroll'));
