const {test}=require('node:test');
const assert=require('node:assert/strict');
const M=require('./rack-model.js');
function fixture(){const p=M.empty();p.rooms=[{id:'room',name:'机房'}];p.racks=[{id:'rack',roomId:'room',name:'01',units:42,location:'',notes:'',length:''}];p.pdus=[{id:'pdu',rackId:'rack',name:'A',count:12,side:'left',socketType:'C13',disabled:[],feed:'UPS A',model:'',rated:'',notes:''}];return p;}
function device(values={}){return {id:'d1',rackId:'rack',name:'服务器',u:20,height:2,face:'both',slot:'full',type:'服务器',brand:'',model:'',serial:'',ip:'',owner:'',notes:'',color:'#5364df',power:[],...values};}
test('demo reproduces three 42U racks and valid power relationships',()=>{const p=M.demo();assert.equal(p.racks.length,3);assert.equal(p.devices.length,17);assert.equal(p.pdus.length,6);assert.deepEqual(M.validate(JSON.parse(JSON.stringify(p))),p);});
test('2U device occupies bottom U and the next U, but can touch neighbors',()=>{const p=fixture();p.devices.push(device());assert.match(M.placementError(p,device({id:'d2',u:21})),/占用/);assert.equal(M.placementError(p,device({id:'d2',u:22})), '');assert.equal(M.placementError(p,device({id:'d2',u:18})), '');assert.equal(M.placementError(p,p.devices[0]),'');});
test('bounds reject fractional, zero, and overflow positions',()=>{const p=fixture();for(const v of [{u:42,height:2},{u:0},{u:1.5},{height:0},{height:43}])assert.match(M.placementError(p,device(v)),/范围/);assert.equal(M.placementError(p,device({u:41})),'');});
test('front/rear half depth devices can share a U, through devices cannot',()=>{const p=fixture();p.devices.push(device({face:'front'}));assert.equal(M.placementError(p,device({id:'d2',face:'rear'})),'');assert.match(M.placementError(p,device({id:'d2',face:'both'})),/占用/);p.devices.push(device({id:'d2',face:'rear'}));assert.equal(M.usedUnits(p,'rack'),2);});
test('power validation rejects duplicate occupied and disabled outlets',()=>{const p=fixture(),power={label:'PSU1',pduId:'pdu',outlet:1,notes:''};p.devices.push(device({power:[power]}));assert.match(M.powerError(p,device({id:'d2',power:[power]})),/占用/);assert.match(M.powerError(p,device({power:[power,{...power,label:'PSU2'}]})),/占用/);assert.equal(M.powerError(p,p.devices[0]),'');p.pdus[0].disabled=[2];assert.match(M.powerError(p,device({power:[{...power,outlet:2}]})),/停用/);});
test('power cannot point to a missing outlet or a different rack',()=>{const p=fixture();assert.match(M.powerError(p,device({power:[{label:'PSU1',pduId:'pdu',outlet:13}]})),/有效插座/);assert.match(M.powerError(p,device({rackId:'other',power:[{label:'PSU1',pduId:'pdu',outlet:1}]})),/本机柜/);});
test('roundtrip includes multiline IP, colors, notes and dual power',()=>{const p=fixture();p.devices.push(device({ip:'192.168.1.1\n192.168.2.1',power:[{label:'PSU1',pduId:'pdu',outlet:1,notes:'白色线'},{label:'PSU2',pduId:'pdu',outlet:2,notes:''}]}));assert.deepEqual(M.validate(JSON.parse(JSON.stringify(p))),p);assert.equal(M.outletUse(p,'pdu',2).power.label,'PSU2');});
test('invalid imports reject overlapping placements, references and duplicate ids',()=>{let p=fixture();p.devices=[device(),device({id:'d2'})];assert.throws(()=>M.validate(p),/占用/);p=fixture();p.racks[0].roomId='absent';assert.throws(()=>M.validate(p),/所属机房/);p=fixture();p.devices=[device({id:'rack'})];assert.throws(()=>M.validate(p),/编号/);assert.throws(()=>M.validate({nodes:[],edges:[]}),/拓扑项目/);});
test('CSV has BOM, quoted multiline values and neutralizes spreadsheet formulas',()=>{const p=fixture();p.devices=[device({name:'=HYPERLINK("test")',ip:'IP1\nIP2'})];const csv=M.csv(p);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('"\'=HYPERLINK(""test"")"'));assert.ok(csv.includes('"IP1\nIP2"'));assert.ok(csv.includes('供电来源'));});
test('CSV creates a row per power input and keeps unpowered devices',()=>{const p=fixture();p.devices=[device({power:[{label:'PSU1',pduId:'pdu',outlet:1},{label:'PSU2',pduId:'pdu',outlet:2}]}),device({id:'d2',u:30})];assert.equal(M.csv(p).split('\r\n').length,4);});

test("one physical power input cannot be assigned twice",()=>{const p=fixture();assert.match(M.powerError(p,device({power:[{label:"PSU1",pduId:"pdu",outlet:1},{label:"psu1",pduId:"pdu",outlet:2}]})),/接口.*已连接/);});

test('half width and face combinations allow four shallow devices at one U',()=>{const p=fixture();p.devices=[device({face:'front',slot:'left',height:1})];for(const [id,face,slot] of [['d2','front','right'],['d3','rear','left'],['d4','rear','right']]){const d=device({id,face,slot,height:1});assert.equal(M.placementError(p,d),'');p.devices.push(d);}assert.equal(M.usedUnits(p,'rack'),1);assert.match(M.placementError(p,device({id:'d5',slot:'full'})),/占用/);assert.match(M.placementError(p,device({id:'d5',slot:'left',face:'both'})),/占用/);assert.equal(M.validate(p).devices.length,4);});
test('old devices default to full width on import',()=>{const p=fixture();const d=device();delete d.slot;p.devices=[d];assert.equal(M.validate(p).devices[0].slot,'full');assert.match(M.placementError(p,device({id:'d2',slot:'right'})),/占用/);});
test('SVG exports complete racks, two U rulers and device-colored sockets',()=>{const E=require('./rack-export.js'),p=fixture();p.devices=[device({slot:'left',name:'A < B',power:[{label:'PSU1',pduId:'pdu',outlet:1}]})];const result=E.svg(p,'room');assert.ok(result.height>1000);assert.ok(result.content.includes('A &lt; B'));assert.equal((result.content.match(/>42<\/text>/g)||[]).length,2);assert.ok(result.content.includes('fill="#5364df"'));assert.notEqual(E.svg(p,'room','rear').content,result.content);assert.throws(()=>E.svg(p,'missing'),/没有机柜/);});

test('quick power uses free PSU names and available sockets',()=>{const p=fixture(),d=device({power:[{label:'PSU1',pduId:'pdu',outlet:1}]});p.devices=[d];p.pdus[0].disabled=[2];assert.deepEqual(M.defaultPower(p,d,'pdu'),{label:'PSU2',pduId:'pdu',outlet:3,notes:''});assert.throws(()=>M.defaultPower(p,d,'pdu',1),/占用/);assert.throws(()=>M.defaultPower(p,d,'pdu',2),/停用/);assert.throws(()=>M.defaultPower(p,{...d,rackId:'other'},'pdu'),/同一机柜/);p.pdus[0].count=2;assert.throws(()=>M.defaultPower(p,d,'pdu'),/没有空闲/);});

function cascadeFixture(){const p=fixture();p.racks.push({...p.racks[0],id:'rack2',name:'02'});p.pdus.push({...p.pdus[0],id:'child',rackId:'rack2',name:'下级 B'});return p;}
test('PDU input supports cross-rack replacement and shared outlet occupancy',()=>{const p=cascadeFixture(),child=p.pdus[1];child.input=M.defaultPduInput(p,child,'pdu',1);assert.equal(child.input.label,'INPUT');assert.equal(M.outletUse(p,'pdu',1).kind,'pdu');assert.match(M.powerError(p,device({power:[{label:'PSU1',pduId:'pdu',outlet:1}]})),/占用/);child.input=M.defaultPduInput(p,child,'pdu',2);assert.equal(M.outletUse(p,'pdu',1),null);assert.deepEqual(M.validate(p),p);assert.ok(M.csv(p).includes('INPUT'));const svg=require('./rack-export.js').svg(p,'room').content;assert.ok(svg.includes('下级 B / INPUT'));delete child.input;assert.equal(M.outletUse(p,'pdu',2),null);});
test('PDU cycles, disabled and occupied inputs are blocked including imports',()=>{const p=cascadeFixture(),a=p.pdus[0],b=p.pdus[1];assert.throws(()=>M.defaultPduInput(p,a,a.id,1),/循环/);b.input=M.defaultPduInput(p,b,a.id,1);assert.throws(()=>M.defaultPduInput(p,a,b.id,1),/循环/);a.disabled=[2];assert.throws(()=>M.defaultPduInput(p,b,a.id,2),/停用/);p.devices=[device({power:[{label:'PSU1',pduId:a.id,outlet:3}]})];assert.throws(()=>M.defaultPduInput(p,b,a.id,3),/占用/);a.input={label:'INPUT',pduId:b.id,outlet:1};assert.throws(()=>M.validate(p),/循环/);});

test('机柜空白拖动平移并阻止误点击，设备和输入框保留原操作',()=>{const source=require('node:fs').readFileSync('racks.js','utf8'),ctx=require('node:vm').createContext({}),handlers={},classes=new Set();require('node:vm').runInContext(source.slice(source.indexOf('function installBoardPan('),source.indexOf("installBoardPan($('#boardScroll'))")),ctx);let captured=false;const scroller={scrollLeft:100,scrollTop:200,clientWidth:500,clientHeight:400,getBoundingClientRect:()=>({left:0,top:0}),classList:{add:x=>classes.add(x),remove:x=>classes.delete(x)},addEventListener:(name,fn)=>handlers[name]=fn,setPointerCapture:()=>captured=true,hasPointerCapture:()=>captured,releasePointerCapture:()=>captured=false};ctx.installBoardPan(scroller);const event=(kind,x,y)=>({button:0,pointerId:1,clientX:x,clientY:y,preventDefault(){},target:{closest:s=>s==='button'?(kind==='device'?{hasAttribute:()=>false}:kind==='emptyU'?{hasAttribute:()=>true}:null):kind==='input'?{}:null}});handlers.pointerdown(event('emptyU',100,100));handlers.pointermove(event('emptyU',60,40));assert.equal(scroller.scrollLeft,140);assert.equal(scroller.scrollTop,260);handlers.pointerup(event('emptyU',60,40));let blocked=false;handlers.click({preventDefault(){},stopImmediatePropagation(){blocked=true;}});assert.equal(blocked,true);assert.equal(classes.size,0);for(const kind of ['device','input']){handlers.pointerdown(event(kind,100,100));handlers.pointermove(event(kind,50,50));assert.equal(scroller.scrollTop,260);}handlers.pointerdown(event('emptyU',100,100));handlers.pointerup(event('emptyU',100,100));handlers.click({preventDefault(){assert.fail('单击应保留上架操作')},stopImmediatePropagation(){}});});
