const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const source=fs.readFileSync('app.js','utf8');
const ipLayout=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function managementIpLines('),source.indexOf('function refreshSelection(')),ipLayout);
test('管理 IP 保留手动换行和中间空行，空值不占空间',()=>{assert.equal(JSON.stringify(ipLayout.managementIpLines({managementIp:'192.168.1.1\n\n10.0.0.1'})),JSON.stringify(['192.168.1.1','','10.0.0.1']));assert.equal(ipLayout.managementIpLines({managementIp:'  '}).length,0);assert.equal(ipLayout.nodeHeight({managementIp:'192.168.1.1'}),80);assert.equal(ipLayout.nodeHeight({managementIp:'192.168.1.1\n10.0.0.1'}),100)});
test('属性栏开始的文本选择在画布释放时不重绘属性面板',()=>{let renders=0;const ctx=vm.createContext({gesture:null,renderInspector:()=>renders++});vm.runInContext(source.slice(source.indexOf('function endGesture('),source.indexOf('canvas.onpointerup=endGesture')),ctx);assert.doesNotThrow(()=>ctx.endGesture({type:'pointerup'}));assert.doesNotThrow(()=>ctx.endGesture({type:'pointercancel'}));assert.equal(renders,0)});
test('画布拖动释放仍保存位置并结束手势',()=>{let saved=0,renders=0;const ctx=vm.createContext({gesture:{type:'nodes',moved:true},persist:()=>saved++,renderGuides:()=>{},renderInspector:()=>renders++,$:()=>({style:{}})});vm.runInContext(source.slice(source.indexOf('function endGesture('),source.indexOf('canvas.onpointerup=endGesture')),ctx);ctx.endGesture({type:'pointerup'});assert.equal(saved,1);assert.equal(renders,1);assert.equal(ctx.gesture,null)});
const grid=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function snapGrid('),source.indexOf('function moveDevices(')),grid);
test('设备位置吸附到 20 像素网格，包括负坐标',()=>{for(const [input,output] of [[13,20],[7,0],[-33,-40],[400,400]])assert.equal(grid.snapGrid(input),output)});
const context=vm.createContext({types:{switch:[],server:[],text:[],region:[]}});
vm.runInContext(source.slice(source.indexOf('function assetDefaults('),source.indexOf('function assetFields(')),context);
vm.runInContext(source.slice(source.indexOf('function validate('),source.indexOf("$('#fileInput').onchange")),context);
function project(){return {version:1,name:'测试拓扑',cables:[{id:'cat6',name:'六类网线',color:'#5683e8'}],nodes:[{id:'a',name:'交换机',type:'switch',brand:'',model:'',x:0,y:0,ports:[{id:'ap',name:'GE1',kind:'RJ45'}]},{id:'b',name:'服务器',type:'server',brand:'',model:'',x:300,y:0,ports:[{id:'bp',name:'ETH1',kind:'RJ45'}]}],edges:[{id:'e',from:'a',fromPort:'ap',to:'b',toPort:'bp',cable:'cat6'}]}}
test('有效项目可 JSON 往返且保留端口连接',()=>assert.equal(context.validate(JSON.parse(JSON.stringify(project()))).edges[0].fromPort,'ap'));
test('旧项目线路带宽默认为空',()=>assert.equal(context.validate(project()).edges[0].bandwidth,''));
test('旧项目默认隐藏带宽，显示选项支持文件往返',()=>{assert.equal(context.validate(project()).edges[0].showBandwidth,false);const p=project();p.edges[0].bandwidth='10 Gbps';p.edges[0].showBandwidth=true;assert.equal(context.validate(JSON.parse(JSON.stringify(p))).edges[0].showBandwidth,true);p.edges[0].showBandwidth='false';assert.throws(()=>context.validate(p),/显示设置无效/)});
test('自定义带宽随项目保存和打开保留',()=>{const p=project();p.edges[0].bandwidth='500 Mbps';assert.equal(context.validate(JSON.parse(JSON.stringify(p))).edges[0].bandwidth,'500 Mbps')});
test('拒绝非法或超长带宽字段',()=>{const p=project();p.edges[0].bandwidth={value:1000};assert.throws(()=>context.validate(p),/文本格式无效/);p.edges[0].bandwidth='1'.repeat(81);assert.throws(()=>context.validate(p),/文本格式无效/)});
test('旧项目自动补齐资产字段并保持原端口',()=>{const p=context.validate(project());for(const value of Object.keys(context.assetDefaults()))assert.equal(p.nodes[0][value],'');assert.equal(p.nodes[0].ports[0].name,'GE1')});
test('设备资产信息经保存打开完整保留',()=>{const p=project();Object.assign(p.nodes[0],{purpose:'核心交换',managementIp:'192.168.10.1',serialNumber:'SN-001',managementProtocol:'HTTPS / SSH',managementPort:'443 / 22',physicalLocation:'机房 A01 / U12',owner:'信息部',supplier:'设备供应商',rackDate:'2026-09-08',warranty:'三年原厂保修\n含上门服务',warrantyUntil:'2029-09-08',notes:'生产设备\n维护前通知'});const expected=JSON.stringify(p.nodes[0]);assert.equal(JSON.stringify(context.validate(JSON.parse(JSON.stringify(p))).nodes[0]),expected.replace(/}$/,',"expanded":false}'))});
test('拒绝非法资产字段，允许多行长备注',()=>{const p=project();p.nodes[0].notes='维护记录\n'.repeat(100);assert.doesNotThrow(()=>context.validate(p));p.nodes[0].managementIp={value:'192.168.1.1'};assert.throws(()=>context.validate(p),/文本格式无效/)});
test('拒绝重复占用端口',()=>{const p=project();p.edges.push({...p.edges[0],id:'e2'});assert.throws(()=>context.validate(p),/重复占用/)});
test('拒绝不存在的端口',()=>{const p=project();p.edges[0].toPort='missing';assert.throws(()=>context.validate(p),/端口缺失/)});
test('拒绝重复设备标识',()=>{const p=project();p.nodes[1].id='a';assert.throws(()=>context.validate(p),/重复/)});
test('拒绝重复端口名称',()=>{const p=project();p.nodes[0].ports.push({id:'ap2',name:'GE1',kind:'RJ45'});assert.throws(()=>context.validate(p),/端口数据无效/)});
test('拒绝非法线材颜色和非有限坐标',()=>{const p=project();p.cables[0].color='red';assert.throws(()=>context.validate(p),/颜色无效/);p.cables[0].color='#000000';p.nodes[0].x=Infinity;assert.throws(()=>context.validate(p),/设备数据无效/)});

test('区域尺寸颜色和文本尺寸经过保存打开保持不变',()=>{const p=project();p.nodes.push({id:'r',type:'region',name:'机房',brand:'',model:'',x:0,y:0,width:400,height:260,color:'#aabbcc',ports:[]},{id:'t',type:'text',name:'备注',brand:'',model:'',x:20,y:20,width:240,height:80,ports:[]});const v=context.validate(JSON.parse(JSON.stringify(p)));assert.equal(v.nodes[2].color,'#aabbcc');assert.equal(v.nodes[2].width,400);assert.equal(v.nodes[3].height,80);p.nodes[2].width=-1;assert.throws(()=>context.validate(p),/尺寸无效/);p.nodes[2].width=400;p.nodes[2].color='red';assert.throws(()=>context.validate(p),/颜色无效/)});
test('从左上角缩放保持右下角固定，限制最小尺寸',()=>{const g={dir:'nw',x:100,y:100,w:320,h:240};const result=grid.resizeBox(g,39,21);assert.equal(result.width,280);assert.equal(result.height,220);assert.equal(result.x+result.width,420);assert.equal(result.y+result.height,340);assert.equal(grid.resizeBox(g,1000,1000).width,80)});
test('复制设备保留属性但生成独立设备和端口标识',()=>{let seq=0;const ctx=vm.createContext({structuredClone,uid:()=>String(++seq)});vm.runInContext(source.slice(source.indexOf('function duplicateNodes('),source.indexOf('function copySelection(')),ctx);const original={id:'old',type:'switch',x:20,y:40,brand:'品牌',managementIp:'10.0.0.1',ports:[{id:'old-port',name:'GE1',kind:'RJ45'}]};const copy=ctx.duplicateNodes([original])[0];assert.notEqual(copy.id,original.id);assert.notEqual(copy.ports[0].id,original.ports[0].id);assert.equal(copy.managementIp,original.managementIp);assert.equal(copy.x,40);copy.ports[0].name='Changed';assert.equal(original.ports[0].name,'GE1')});

test('端口自然排序正确处理数字，排序保留端口对象和原数组',()=>{const ctx=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function sortPorts('),source.indexOf('function portRows(')),ctx);const ports=[{id:'a',name:'GE10',kind:'RJ45'},{id:'b',name:'GE2',kind:'RJ45'},{id:'c',name:'GE1',kind:'SFP'}];assert.equal(ctx.sortPorts(ports,'asc',()=>false).map(p=>p.name).join(','),'GE1,GE2,GE10');assert.equal(ctx.sortPorts(ports,'desc',()=>false).map(p=>p.name).join(','),'GE10,GE2,GE1');assert.equal(ctx.sortPorts(ports,'used',p=>p.id==='a')[0],ports[0]);assert.equal(ports[0].name,'GE10');assert.equal(new Set(ctx.sortPorts(ports,'kind',()=>false).map(p=>p.id)).size,3)});
