const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const source=fs.readFileSync('app.js','utf8');
const ipLayout=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function managementIpLines('),source.indexOf('function refreshSelection(')),ipLayout);
test('管理 IP 保留手动换行和中间空行，空值不占空间',()=>{assert.equal(JSON.stringify(ipLayout.managementIpLines({managementIp:'192.168.1.1\n\n10.0.0.1'})),JSON.stringify(['192.168.1.1','','10.0.0.1']));assert.equal(ipLayout.managementIpLines({managementIp:'  '}).length,0);assert.equal(ipLayout.nodeHeight({managementIp:'192.168.1.1'}),80);assert.equal(ipLayout.nodeHeight({managementIp:'192.168.1.1\n10.0.0.1'}),100)});
test('属性栏开始的文本选择在画布释放时不重绘属性面板',()=>{let renders=0;const ctx=vm.createContext({gesture:null,renderInspector:()=>renders++});vm.runInContext(source.slice(source.indexOf('function endGesture('),source.indexOf('canvas.onpointerup=endGesture')),ctx);assert.doesNotThrow(()=>ctx.endGesture({type:'pointerup'}));assert.doesNotThrow(()=>ctx.endGesture({type:'pointercancel'}));assert.equal(renders,0)});
test('画布拖动释放仍保存位置并结束手势',()=>{let saved=0,renders=0;const ctx=vm.createContext({gesture:{type:'nodes',moved:true},persist:()=>saved++,renderGuides:()=>{},renderInspector:()=>renders++,$:()=>({style:{}})});vm.runInContext(source.slice(source.indexOf('function endGesture('),source.indexOf('canvas.onpointerup=endGesture')),ctx);ctx.endGesture({type:'pointerup'});assert.equal(saved,1);assert.equal(renders,1);assert.equal(ctx.gesture,null)});
const grid=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function snapGrid('),source.indexOf('function moveDevices(')),grid);
test('设备位置吸附到 20 像素网格，包括负坐标',()=>{for(const [input,output] of [[13,20],[7,0],[-33,-40],[400,400]])assert.equal(grid.snapGrid(input),output)});
const context=vm.createContext({types:{switch:[],server:[],text:[],region:[]}});
vm.runInContext(source.slice(source.indexOf('function assetDefaults('),source.indexOf('function assetFields(')),context);
vm.runInContext(source.slice(source.indexOf('function validate('),source.indexOf("$('#fileInput').onchange")),context);
function project(){return {version:1,name:'测试拓扑',cables:[{id:'cat6',name:'六类网线',color:'#5683e8'}],nodes:[{id:'a',name:'交换机',type:'switch',brand:'',model:'',x:0,y:0,ports:[{id:'ap',name:'GE1',kind:'RJ45'}]},{id:'b',name:'服务器',type:'server',brand:'',model:'',x:300,y:0,ports:[{id:'bp',name:'ETH1',kind:'RJ45'}]}],edges:[{id:'e',from:'a',fromPort:'ap',to:'b',toPort:'bp',cable:'cat6'}]}}
test('有效项目可 JSON 往返且保留端口连接',()=>assert.equal(context.validate(JSON.parse(JSON.stringify(project()))).edges[0].fromPort,'ap'));
test('旧项目线路带宽默认为空',()=>assert.equal(context.validate(project()).edges[0].bandwidth,''));
test('旧项目默认隐藏带宽，显示选项支持文件往返',()=>{assert.equal(context.validate(project()).edges[0].showBandwidth,false);const p=project();p.edges[0].bandwidth='10 Gbps';p.edges[0].showBandwidth=true;assert.equal(context.validate(JSON.parse(JSON.stringify(p))).edges[0].showBandwidth,true);p.edges[0].showBandwidth='false';assert.throws(()=>context.validate(p),/显示设置无效/)});
test('自定义带宽随项目保存和打开保留',()=>{const p=project();p.edges[0].bandwidth='500 Mbps';assert.equal(context.validate(JSON.parse(JSON.stringify(p))).edges[0].bandwidth,'500 Mbps')});
test('拒绝非法或超长带宽字段',()=>{const p=project();p.edges[0].bandwidth={value:1000};assert.throws(()=>context.validate(p),/文本格式无效/);p.edges[0].bandwidth='1'.repeat(81);assert.throws(()=>context.validate(p),/文本格式无效/)});
test('旧项目自动补齐资产字段并保持原端口',()=>{const p=context.validate(project());for(const value of Object.keys(context.assetDefaults()))assert.equal(p.nodes[0][value],'');assert.equal(p.nodes[0].ports[0].name,'GE1')});
test('设备资产信息经保存打开完整保留',()=>{const p=project();Object.assign(p.nodes[0],{purpose:'核心交换',managementIp:'192.168.10.1',serialNumber:'SN-001',managementProtocol:'HTTPS / SSH',managementPort:'443 / 22',physicalLocation:'机房 A01 / U12',owner:'信息部',supplier:'设备供应商',rackDate:'2026-09-08',warranty:'三年原厂保修\n含上门服务',warrantyUntil:'2029-09-08',notes:'生产设备\n维护前通知'});const expected=JSON.stringify(p.nodes[0]);assert.equal(JSON.stringify(context.validate(JSON.parse(JSON.stringify(p))).nodes[0]),expected.replace(/}$/,',"expanded":false}'))});
test('拒绝非法资产字段，允许多行长备注',()=>{const p=project();p.nodes[0].notes='维护记录\n'.repeat(100);assert.doesNotThrow(()=>context.validate(p));p.nodes[0].managementIp={value:'192.168.1.1'};assert.throws(()=>context.validate(p),/文本格式无效/)});
test('拒绝重复占用端口',()=>{const p=project();p.edges.push({...p.edges[0],id:'e2'});assert.throws(()=>context.validate(p),/重复占用/)});
test('拒绝不存在的端口',()=>{const p=project();p.edges[0].toPort='missing';assert.throws(()=>context.validate(p),/端口缺失/)});
test('拒绝重复设备标识',()=>{const p=project();p.nodes[1].id='a';assert.throws(()=>context.validate(p),/重复/)});
test('拒绝重复端口名称',()=>{const p=project();p.nodes[0].ports.push({id:'ap2',name:'GE1',kind:'RJ45'});assert.throws(()=>context.validate(p),/端口数据无效/)});
test('拒绝非法线材颜色和非有限坐标',()=>{const p=project();p.cables[0].color='red';assert.throws(()=>context.validate(p),/颜色无效/);p.cables[0].color='#000000';p.nodes[0].x=Infinity;assert.throws(()=>context.validate(p),/设备数据无效/)});

test('区域尺寸颜色和文本尺寸经过保存打开保持不变',()=>{const p=project();p.nodes.push({id:'r',type:'region',name:'机房',brand:'',model:'',x:0,y:0,width:400,height:260,color:'#aabbcc',ports:[]},{id:'t',type:'text',name:'备注',brand:'',model:'',x:20,y:20,width:240,height:80,ports:[]});const v=context.validate(JSON.parse(JSON.stringify(p)));assert.equal(v.nodes[2].color,'#aabbcc');assert.equal(v.nodes[2].width,400);assert.equal(v.nodes[3].height,80);p.nodes[2].width=-1;assert.throws(()=>context.validate(p),/尺寸无效/);p.nodes[2].width=400;p.nodes[2].color='red';assert.throws(()=>context.validate(p),/颜色无效/)});
test('从左上角缩放保持右下角固定，限制最小尺寸',()=>{const g={dir:'nw',x:100,y:100,w:320,h:240};const result=grid.resizeBox(g,39,21);assert.equal(result.width,280);assert.equal(result.height,220);assert.equal(result.x+result.width,420);assert.equal(result.y+result.height,340);assert.equal(grid.resizeBox(g,1000,1000).width,80)});
test('复制设备保留属性但生成独立设备和端口标识',()=>{let seq=0;const ctx=vm.createContext({structuredClone,uid:()=>String(++seq)});vm.runInContext(source.slice(source.indexOf('function duplicateNodes('),source.indexOf('function copySelection(')),ctx);const original={id:'old',type:'switch',x:20,y:40,brand:'品牌',managementIp:'10.0.0.1',ports:[{id:'old-port',name:'GE1',kind:'RJ45'}]};const copy=ctx.duplicateNodes([original])[0];assert.notEqual(copy.id,original.id);assert.notEqual(copy.ports[0].id,original.ports[0].id);assert.equal(copy.managementIp,original.managementIp);assert.equal(copy.x,40);copy.ports[0].name='Changed';assert.equal(original.ports[0].name,'GE1')});

test('端口自然排序正确处理数字，排序保留端口对象和原数组',()=>{const ctx=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function sortPorts('),source.indexOf('function portRows(')),ctx);const ports=[{id:'a',name:'GE10',kind:'RJ45'},{id:'b',name:'GE2',kind:'RJ45'},{id:'c',name:'GE1',kind:'SFP'}];assert.equal(ctx.sortPorts(ports,'asc',()=>false).map(p=>p.name).join(','),'GE1,GE2,GE10');assert.equal(ctx.sortPorts(ports,'desc',()=>false).map(p=>p.name).join(','),'GE10,GE2,GE1');assert.equal(ctx.sortPorts(ports,'used',p=>p.id==='a')[0],ports[0]);assert.equal(ports[0].name,'GE10');assert.equal(new Set(ctx.sortPorts(ports,'kind',()=>false).map(p=>p.id)).size,3)});

test('连线按对端位置排序，避免创建顺序造成上下交叉',()=>{const nodes=[{id:'target',x:400,y:100},{id:'upper',x:0,y:0},{id:'lower',x:0,y:200}];const edges=[{id:'lower-edge',from:'lower',to:'target'},{id:'upper-edge',from:'upper',to:'target'}];const ctx=vm.createContext({model:{edges,nodes},nodeBy:id=>nodes.find(n=>n.id===id),nodeHeight:()=>80,nodeWidth:()=>160});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);const upper=ctx.route(edges[1]),lower=ctx.route(edges[0]);assert.ok(upper.q.y<lower.q.y);assert.ok(upper.points.length<=3);assert.ok(lower.points.length<=3);nodes[1].y=220;nodes[2].y=0;assert.ok(ctx.route(edges[0]).q.y<ctx.route(edges[1]).q.y)});
test('纵向连线按对端左右位置排序，多条平行线两端顺序一致',()=>{const nodes=[{id:'target',x:100,y:400},{id:'left',x:0,y:0},{id:'right',x:200,y:0}];const edges=[{id:'r',from:'right',to:'target'},{id:'l',from:'left',to:'target'},{id:'l2',from:'target',to:'left'}];const ctx=vm.createContext({model:{edges,nodes},nodeBy:id=>nodes.find(n=>n.id===id),nodeHeight:()=>80,nodeWidth:()=>160});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);assert.ok(ctx.route(edges[1]).q.x<ctx.route(edges[0]).q.x);assert.ok(ctx.route(edges[1]).p.x<ctx.route(edges[2]).q.x);assert.ok(ctx.route(edges[1]).q.x<ctx.route(edges[2]).p.x)});

test('正交线路绕过中间设备，所有线段不穿过障碍',()=>{const ctx=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function connectionOffset(')),ctx);const boxes=[{x:80,y:-30,w:100,h:60},{x:200,y:20,w:60,h:100}],path=ctx.avoidDevices([{x:0,y:0},{x:320,y:0}],boxes);assert.ok(path.length>2);for(let i=1;i<path.length;i++){assert.ok(path[i].x===path[i-1].x||path[i].y===path[i-1].y);assert.equal(ctx.segmentBlocked(path[i-1],path[i],boxes),false)}assert.equal(path[0].x,0);assert.equal(path.at(-1).x,320)});

test('右上目标可从源设备右侧出线，一个直角到达且避开上方设备',()=>{const nodes=[{id:'a',x:0,y:400},{id:'b',x:360,y:0},{id:'obstacle',x:0,y:220}],edges=[{id:'ab',from:'a',to:'b'}];const ctx=vm.createContext({model:{nodes,edges},nodeBy:id=>nodes.find(n=>n.id===id),nodeWidth:()=>160,nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);const r=ctx.route(edges[0]);assert.equal(r.p.x,160);assert.equal(r.q.y,80);assert.equal(r.points.length,3);assert.equal(ctx.segmentBlocked(r.points[0],r.points[1],[{x:0,y:220,w:160,h:80}]),false)});
test('同高度设备直接连接，无多余折角',()=>{const nodes=[{id:'a',x:0,y:0},{id:'b',x:360,y:0}],edges=[{id:'ab',from:'a',to:'b'}];const ctx=vm.createContext({model:{nodes,edges},nodeBy:id=>nodes.find(n=>n.id===id),nodeWidth:()=>160,nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);assert.equal(ctx.route(edges[0]).points.length,2)});

test('对齐设备连接数不同也保持直线，消除端口偏移导致的小折角',()=>{const nodes=[{id:'a',x:100,y:0},{id:'b',x:100,y:240},{id:'c',x:400,y:240}],edges=[{id:'ab',from:'a',to:'b'},{id:'ac',from:'a',to:'c'}];const ctx=vm.createContext({model:{nodes,edges},nodeBy:id=>nodes.find(n=>n.id===id),nodeWidth:()=>160,nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);const path=ctx.route(edges[0]).points;assert.equal(path.length,2);assert.equal(path[0].x,path[1].x);nodes[1].x=120;assert.equal(ctx.route(edges[0]).points.length,2)});

test('同高度扇入线路按方向角排序，远端在上近端在下且不依赖创建顺序',()=>{const ctx=vm.createContext({nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function compareSideTargets('),source.indexOf('function route(')),ctx);const target={x:800,y:0},sources=[{x:400,y:300},{x:0,y:300},{x:200,y:300}];assert.equal(sources.sort((a,b)=>ctx.compareSideTargets(target,{x:-1,y:0},a,b)).map(n=>n.x).join(','),'0,200,400');const above=sources.map(n=>({...n,y:-300}));assert.equal(above.sort((a,b)=>ctx.compareSideTargets(target,{x:-1,y:0},a,b)).map(n=>n.x).join(','),'400,200,0')});
test('同列设备汇入上下边缘按方向角安排左右顺序',()=>{const ctx=vm.createContext({nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function compareSideTargets('),source.indexOf('function route(')),ctx);const target={x:0,y:0},sources=[{x:300,y:200},{x:300,y:600},{x:300,y:400}];assert.equal(sources.sort((a,b)=>ctx.compareSideTargets(target,{x:0,y:1},a,b)).map(n=>n.y).join(','),'600,400,200')});

test('三条同排设备汇入右侧设备的实际折线互不交叉',()=>{const nodes=[{id:'t',x:900,y:0},{id:'a',x:0,y:300},{id:'b',x:260,y:300},{id:'c',x:520,y:300}],edges=['c','a','b'].map(id=>({id,from:id,to:'t'})),ctx=vm.createContext({model:{nodes,edges},nodeBy:id=>nodes.find(n=>n.id===id),nodeWidth:()=>160,nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);const paths=edges.map(e=>ctx.route(e).points);for(let a=0;a<paths.length;a++)for(let b=a+1;b<paths.length;b++)for(let i=1;i<paths[a].length;i++)for(let j=1;j<paths[b].length;j++){const p=paths[a][i-1],q=paths[a][i],r=paths[b][j-1],s=paths[b][j];const cross=(v,w,h,k)=>v.x===w.x&&h.y===k.y&&v.x>Math.min(h.x,k.x)&&v.x<Math.max(h.x,k.x)&&h.y>Math.min(v.y,w.y)&&h.y<Math.max(v.y,w.y);assert.equal(cross(p,q,r,s)||cross(r,s,p,q),false)}});

test('整体选路分离灰色直线与扇入线路，并消除右侧交叉',()=>{const nodes=[{id:'hub',x:1400,y:0},{id:'gray',x:0,y:20},{id:'a',x:650,y:320},{id:'b',x:900,y:320},{id:'c',x:1150,y:320},{id:'right1',x:1700,y:320},{id:'right2',x:1900,y:320}],edges=['gray','a','b','c','right2','right1'].map(id=>({id,from:id,to:'hub'})),ctx=vm.createContext({model:{nodes,edges},nodeBy:id=>nodes.find(n=>n.id===id),nodeWidth:()=>160,nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);ctx.prepareRoutes();const paths=edges.map(e=>ctx.route(e).points);for(let i=0;i<paths.length;i++)for(let j=i+1;j<paths.length;j++)assert.equal(ctx.lineConflict(paths[i],paths[j]),0,edges[i].id+' / '+edges[j].id);for(let i=0;i<paths.length;i++){const boxes=nodes.filter(n=>n.id!==edges[i].from&&n.id!==edges[i].to).map(n=>({...n,w:160,h:80}));for(let k=1;k<paths[i].length;k++)assert.equal(ctx.segmentBlocked(paths[i][k-1],paths[i][k],boxes),false)}const before=ctx.route(edges[0]).d;nodes[1].y+=40;ctx.prepareRoutes();assert.notEqual(ctx.route(edges[0]).d,before)});

test('八条连接的汇聚设备将19排在18上方，均从右侧单折角出线',()=>{const nodes=[{id:'hub',x:800,y:200},{id:'top',x:800,y:0},{id:'left',x:0,y:220},{id:'a',x:100,y:600},{id:'b',x:340,y:600},{id:'c',x:580,y:600},{id:'bottom',x:800,y:650},{id:'18',x:1060,y:620},{id:'19',x:1380,y:700}],edges=nodes.slice(1).map(n=>({id:n.id,from:'hub',to:n.id})),ctx=vm.createContext({model:{nodes,edges},nodeBy:id=>nodes.find(n=>n.id===id),nodeWidth:()=>160,nodeHeight:()=>80});vm.runInContext(source.slice(source.indexOf('function segmentBlocked('),source.indexOf('function endpointLayout(')),ctx);ctx.prepareRoutes();const a=ctx.route(edges.find(e=>e.id==='18')),b=ctx.route(edges.find(e=>e.id==='19'));assert.equal(a.p.x,960);assert.equal(b.p.x,960);assert.ok(b.p.y<a.p.y);assert.equal(a.points.length,3);assert.equal(b.points.length,3);assert.equal(ctx.lineConflict(a.points,b.points),0)});

test('区域文字大小和颜色保存恢复，兼容旧项目并拒绝无效值',()=>{const p=project();p.nodes.push({id:'region',type:'region',name:'区域',brand:'',model:'',x:0,y:0,ports:[],fontSize:28,textColor:'#e65100'});const result=context.validate(JSON.parse(JSON.stringify(p)));assert.equal(result.nodes[2].fontSize,28);assert.equal(result.nodes[2].textColor,'#e65100');delete p.nodes[2].fontSize;delete p.nodes[2].textColor;const old=context.validate(p);assert.equal(old.nodes[2].fontSize,12);assert.equal(old.nodes[2].textColor,'#40516b');p.nodes[2].fontSize=100;assert.throws(()=>context.validate(p),/文字大小/);p.nodes[2].fontSize=20;p.nodes[2].textColor='red';assert.throws(()=>context.validate(p),/文字颜色/)});

test('拖动预览多选平移保持路线形状，单端移动保持端点及正交线段',()=>{const ctx=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function compactPath('),source.indexOf('function pathScore(')),ctx);vm.runInContext(source.slice(source.indexOf('function dragPath('),source.indexOf('function queueDragPreview(')),ctx);const base=[{x:0,y:0},{x:100,y:0},{x:100,y:200}],moved=ctx.dragPath(base,20,40,20,40);assert.equal(JSON.stringify(moved),JSON.stringify(base.map(p=>({x:p.x+20,y:p.y+40}))));const one=ctx.dragPath(base,60,40,0,0);assert.equal(one[0].x,60);assert.equal(one[0].y,40);assert.equal(one.at(-1).x,100);assert.equal(one.at(-1).y,200);for(let i=1;i<one.length;i++)assert.ok(one[i].x===one[i-1].x||one[i].y===one[i-1].y)});
test('连续拖动事件合并为一帧预览',()=>{let frames=0,callback;const g={preview:{nodes:[],edges:[]}},ctx=vm.createContext({gesture:g,requestAnimationFrame:fn=>{frames++;callback=fn;return frames}});vm.runInContext(source.slice(source.indexOf('function queueDragPreview('),source.indexOf('function moveDevices(')),ctx);for(let i=0;i<100;i++)ctx.queueDragPreview(g);assert.equal(frames,1);callback();assert.equal(g.frame,null)});

function pointerFixture(nodes){const ctx=vm.createContext({canvas:{focus(){},setPointerCapture(){}},model:{nodes},nodeBy:id=>nodes.find(n=>n.id===id),mode:'select',space:false,view:{x:10,y:20,z:1},selected:new Set(),selectedEdge:null,source:null,point:e=>({x:e.clientX,y:e.clientY}),isAnnotation:n=>['region','text'].includes(n.type),refreshSelection(){},renderInspector(){},render(){}});vm.runInContext(source.slice(source.indexOf('function isLockedRegion('),source.indexOf('function toggleRegionLock(')),ctx);vm.runInContext(source.slice(source.indexOf('canvas.onpointerdown='),source.indexOf('canvas.onpointermove=')),ctx);ctx.down=(id,shift=false)=>ctx.canvas.onpointerdown({button:0,shiftKey:shift,clientX:100,clientY:100,pointerId:1,preventDefault(){},target:{closest:s=>s==='[data-node]'&&id?{dataset:{node:id}}:null}});return ctx;}
test('选择工具空白与锁定区域拖动平移，Shift 保留框选',()=>{const ctx=pointerFixture([{id:'r',type:'region',locked:true,x:0,y:0}]);ctx.down();assert.equal(ctx.gesture.type,'pan');ctx.down('r');assert.equal(ctx.gesture.type,'pan');assert.equal(ctx.selected.size,0);ctx.down(undefined,true);assert.equal(ctx.gesture.type,'box');ctx.down('r',true);assert.equal(ctx.gesture.type,'box');});
test('移动设备和未锁定区域时，多选中锁定区域不跟随移动',()=>{const ctx=pointerFixture([{id:'d',type:'switch',x:20,y:20},{id:'r',type:'region',locked:true,x:0,y:0},{id:'u',type:'region',x:0,y:0}]);ctx.selected=new Set(['d','r']);ctx.down('d');assert.equal(ctx.gesture.type,'nodes');assert.deepEqual(Array.from(ctx.gesture.positions,p=>p.id),['d']);ctx.down('u');assert.equal(ctx.gesture.type,'nodes');assert.deepEqual(Array.from(ctx.gesture.positions,p=>p.id),['u']);});

test('连线模式可平移空白及锁定区域，保留连线起点',()=>{const ctx=pointerFixture([{id:'r',type:'region',locked:true,x:0,y:0},{id:'d',type:'switch',x:20,y:20}]);ctx.mode='connect';ctx.source='d';for(const id of [undefined,'r']){ctx.down(id);assert.equal(ctx.gesture.type,'pan');assert.equal(ctx.mode,'connect');assert.equal(ctx.source,'d');}ctx.down('d');assert.equal(ctx.gesture.type,'connect-node');});
test('双击区域框退出连线或平移，不受锁定状态影响',()=>{for(const locked of [false,true])for(const mode of ['connect','pan','select']){const node={id:'r',type:'region',locked},target={closest:s=>s==='[data-node]'?{dataset:{node:'r'}}:null},ctx=vm.createContext({canvas:{},document:{elementFromPoint:()=>target},nodeBy:()=>node,mode,source:'d',renderInspector(){},setMode(value){ctx.mode=value;ctx.source=null;}});vm.runInContext(source.slice(source.indexOf('canvas.ondblclick='),source.indexOf('function editNodeName(')),ctx);ctx.canvas.ondblclick({clientX:0,clientY:0,target});assert.equal(ctx.mode,'select');assert.equal(ctx.source,null);}});

test('连线模式拖设备平移画布、不移动设备或触发误连；点击仍可连线',()=>{const d={id:'d',type:'switch',x:20,y:20},ctx=pointerFixture([d]);ctx.mode='connect';ctx.$=()=>({style:{}});ctx.persist=()=>assert.fail('不应保存位置');ctx.checkpoint=()=>assert.fail('不应创建移动历史');ctx.moveDevices=()=>assert.fail('不应移动设备');ctx.transform=()=>{};let connection=null;ctx.openConnection=(a,b)=>connection=[a,b];vm.runInContext(source.slice(source.indexOf('canvas.onpointermove='),source.indexOf('function snapGrid(')),ctx);vm.runInContext(source.slice(source.indexOf('function endGesture('),source.indexOf('canvas.onpointerup=endGesture')),ctx);ctx.source='first';ctx.down('d');ctx.canvas.onpointermove({clientX:180,clientY:160});ctx.endGesture({type:'pointerup'});assert.equal(ctx.mode,'connect');assert.equal(ctx.source,'first');assert.equal(connection,null);assert.equal(ctx.view.x,90);assert.equal(ctx.view.y,80);assert.equal(d.x,20);assert.equal(d.y,20);ctx.down('d');ctx.endGesture({type:'pointerup'});assert.deepEqual(connection,['first','d']);});

test('连线模式拖动区域框、文本和线路均平移，不改变图元',()=>{for(const type of ['region','text','edge']){const n={id:'n',type,x:0,y:0},ctx=pointerFixture([n]);ctx.mode='connect';ctx.source='first';ctx.transform=()=>{};vm.runInContext(source.slice(source.indexOf('canvas.onpointermove='),source.indexOf('function snapGrid(')),ctx);if(type==='edge')ctx.canvas.onpointerdown({button:0,clientX:100,clientY:100,pointerId:1,preventDefault(){},target:{closest:s=>s==='[data-edge]'?{dataset:{edge:'line'}}:null}});else ctx.down('n');ctx.canvas.onpointermove({clientX:140,clientY:150});assert.equal(ctx.view.x,50);assert.equal(ctx.view.y,70);assert.equal(ctx.mode,'connect');assert.equal(ctx.source,'first');assert.equal(n.x,0);assert.equal(n.y,0);assert.equal(ctx.gesture.id,null);}});

test('空白和锁定区域单击清除选择，拖动平移或取消手势保留选择',()=>{for(const id of [undefined,'r'])for(const action of ['click','drag','cancel']){const ctx=pointerFixture([{id:'r',type:'region',locked:true,x:0,y:0}]);ctx.selected.add('d');ctx.selectedEdge='line';ctx.$=()=>({style:{}});ctx.transform=()=>{};vm.runInContext(source.slice(source.indexOf('canvas.onpointermove='),source.indexOf('function snapGrid(')),ctx);vm.runInContext(source.slice(source.indexOf('function endGesture('),source.indexOf('canvas.onpointerup=endGesture')),ctx);ctx.down(id);if(action==='drag')ctx.canvas.onpointermove({clientX:140,clientY:160});ctx.endGesture({type:action==='cancel'?'pointercancel':'pointerup'});assert.equal(ctx.selected.size,action==='click'?0:1);assert.equal(ctx.selectedEdge,action==='click'?null:'line');}});

test('连线模式点击已有线路不选中线路、不改变连线起点',()=>{const ctx=pointerFixture([]);ctx.mode='connect';ctx.source='device-a';ctx.$=()=>({style:{}});vm.runInContext(source.slice(source.indexOf('function endGesture('),source.indexOf('canvas.onpointerup=endGesture')),ctx);ctx.canvas.onpointerdown({button:0,clientX:100,clientY:100,pointerId:1,preventDefault(){},target:{closest:s=>s==='[data-edge]'?{dataset:{edge:'line'}}:null}});ctx.endGesture({type:'pointerup'});assert.equal(ctx.selectedEdge,null);assert.equal(ctx.source,'device-a');assert.equal(ctx.mode,'connect');});

test('Esc 优先取消选择或连线起点，无选择时才退出连线',()=>{let exits=0;const ctx=vm.createContext({selected:new Set(['device']),selectedEdge:null,source:null,mode:'select',render(){},renderInspector(){},setMode:m=>{ctx.mode=m;},document:{body:{classList:{contains:()=>true}}},exitCanvasFullscreen:()=>exits++});vm.runInContext(source.slice(source.indexOf('function escapeSelection('),source.indexOf("document.addEventListener('keydown',e=>")),ctx);ctx.escapeSelection();assert.equal(ctx.selected.size,0);assert.equal(ctx.mode,'select');assert.equal(exits,0);ctx.mode='connect';ctx.source='device';ctx.escapeSelection();assert.equal(ctx.source,null);assert.equal(ctx.mode,'connect');assert.equal(exits,0);ctx.escapeSelection();assert.equal(ctx.mode,'select');assert.equal(exits,0);ctx.selectedEdge='edge';ctx.escapeSelection();assert.equal(ctx.selectedEdge,null);assert.equal(exits,0);ctx.escapeSelection();assert.equal(exits,1);});

test('所有端口引导线先于标签绘制，避免后绘制的线穿过数字',()=>{const ctx=vm.createContext({esc:x=>x});vm.runInContext(source.slice(source.indexOf('function labelMarkup('),source.indexOf('function renderEdges(')),ctx);const labels=['orange','black'].map((color,i)=>({edgeId:'e'+i,name:'5',color,point:{x:10,y:0},target:{x:10,y:100},x:0,y:20,w:30,h:22}));const svg=ctx.labelMarkup(labels);assert.ok(svg.lastIndexOf('<path')<svg.indexOf('<rect'));assert.equal((svg.match(/class="endpoint-leader"/g)||[]).length,2);assert.equal((svg.match(/class="endpoint-label /g)||[]).length,2);});
